// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Answer is the predicate function for answer builders.
type Answer func(*sql.Selector)

// Club is the predicate function for club builders.
type Club func(*sql.Selector)

// Question is the predicate function for question builders.
type Question func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
