// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"su-organization-matching/server/ent/answer"
	"su-organization-matching/server/ent/question"
	"su-organization-matching/server/ent/user"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// AnswerCreate is the builder for creating a Answer entity.
type AnswerCreate struct {
	config
	mutation *AnswerMutation
	hooks    []Hook
}

// SetAnswerText sets the "answer_text" field.
func (_c *AnswerCreate) SetAnswerText(v string) *AnswerCreate {
	_c.mutation.SetAnswerText(v)
	return _c
}

// SetSubmittedAt sets the "submitted_at" field.
func (_c *AnswerCreate) SetSubmittedAt(v time.Time) *AnswerCreate {
	_c.mutation.SetSubmittedAt(v)
	return _c
}

// SetNillableSubmittedAt sets the "submitted_at" field if the given value is not nil.
func (_c *AnswerCreate) SetNillableSubmittedAt(v *time.Time) *AnswerCreate {
	if v != nil {
		_c.SetSubmittedAt(*v)
	}
	return _c
}

// SetQuestionID sets the "question" edge to the Question entity by ID.
func (_c *AnswerCreate) SetQuestionID(id int) *AnswerCreate {
	_c.mutation.SetQuestionID(id)
	return _c
}

// SetQuestion sets the "question" edge to the Question entity.
func (_c *AnswerCreate) SetQuestion(v *Question) *AnswerCreate {
	return _c.SetQuestionID(v.ID)
}

// SetUserID sets the "user" edge to the User entity by ID.
func (_c *AnswerCreate) SetUserID(id int) *AnswerCreate {
	_c.mutation.SetUserID(id)
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *AnswerCreate) SetUser(v *User) *AnswerCreate {
	return _c.SetUserID(v.ID)
}

// Mutation returns the AnswerMutation object of the builder.
func (_c *AnswerCreate) Mutation() *AnswerMutation {
	return _c.mutation
}

// Save creates the Answer in the database.
func (_c *AnswerCreate) Save(ctx context.Context) (*Answer, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AnswerCreate) SaveX(ctx context.Context) *Answer {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AnswerCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AnswerCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *AnswerCreate) defaults() {
	if _, ok := _c.mutation.SubmittedAt(); !ok {
		v := answer.DefaultSubmittedAt()
		_c.mutation.SetSubmittedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *AnswerCreate) check() error {
	if _, ok := _c.mutation.AnswerText(); !ok {
		return &ValidationError{Name: "answer_text", err: errors.New(`ent: missing required field "Answer.answer_text"`)}
	}
	if _, ok := _c.mutation.SubmittedAt(); !ok {
		return &ValidationError{Name: "submitted_at", err: errors.New(`ent: missing required field "Answer.submitted_at"`)}
	}
	if len(_c.mutation.QuestionIDs()) == 0 {
		return &ValidationError{Name: "question", err: errors.New(`ent: missing required edge "Answer.question"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "Answer.user"`)}
	}
	return nil
}

func (_c *AnswerCreate) sqlSave(ctx context.Context) (*Answer, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AnswerCreate) createSpec() (*Answer, *sqlgraph.CreateSpec) {
	var (
		_node = &Answer{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(answer.Table, sqlgraph.NewFieldSpec(answer.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.AnswerText(); ok {
		_spec.SetField(answer.FieldAnswerText, field.TypeString, value)
		_node.AnswerText = value
	}
	if value, ok := _c.mutation.SubmittedAt(); ok {
		_spec.SetField(answer.FieldSubmittedAt, field.TypeTime, value)
		_node.SubmittedAt = value
	}
	if nodes := _c.mutation.QuestionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   answer.QuestionTable,
			Columns: []string{answer.QuestionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(question.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.question_answers = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   answer.UserTable,
			Columns: []string{answer.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.user_answers = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// AnswerCreateBulk is the builder for creating many Answer entities in bulk.
type AnswerCreateBulk struct {
	config
	err      error
	builders []*AnswerCreate
}

// Save creates the Answer entities in the database.
func (_c *AnswerCreateBulk) Save(ctx context.Context) ([]*Answer, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Answer, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AnswerMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AnswerCreateBulk) SaveX(ctx context.Context) []*Answer {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AnswerCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AnswerCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
