// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"su-organization-matching/server/ent/answer"
	"su-organization-matching/server/ent/question"
	"su-organization-matching/server/ent/user"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// Answer is the model entity for the Answer schema.
type Answer struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// QuestionID holds the value of the "question_id" field.
	QuestionID int `json:"question_id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int `json:"user_id,omitempty"`
	// AnswerText holds the value of the "answer_text" field.
	AnswerText string `json:"answer_text,omitempty"`
	// SubmittedAt holds the value of the "submitted_at" field.
	SubmittedAt time.Time `json:"submitted_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the AnswerQuery when eager-loading is set.
	Edges        AnswerEdges `json:"edges"`
	selectValues sql.SelectValues
}

// AnswerEdges holds the relations/edges for other nodes in the graph.
type AnswerEdges struct {
	// Question holds the value of the question edge.
	Question *Question `json:"question,omitempty"`
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// QuestionOrErr returns the Question value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e AnswerEdges) QuestionOrErr() (*Question, error) {
	if e.Question != nil {
		return e.Question, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: question.Label}
	}
	return nil, &NotLoadedError{edge: "question"}
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e AnswerEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Answer) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case answer.FieldID, answer.FieldQuestionID, answer.FieldUserID:
			values[i] = new(sql.NullInt64)
		case answer.FieldAnswerText:
			values[i] = new(sql.NullString)
		case answer.FieldSubmittedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Answer fields.
func (_m *Answer) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case answer.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case answer.FieldQuestionID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field question_id", values[i])
			} else if value.Valid {
				_m.QuestionID = int(value.Int64)
			}
		case answer.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = int(value.Int64)
			}
		case answer.FieldAnswerText:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field answer_text", values[i])
			} else if value.Valid {
				_m.AnswerText = value.String
			}
		case answer.FieldSubmittedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field submitted_at", values[i])
			} else if value.Valid {
				_m.SubmittedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Answer.
// This includes values selected through modifiers, order, etc.
func (_m *Answer) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryQuestion queries the "question" edge of the Answer entity.
func (_m *Answer) QueryQuestion() *QuestionQuery {
	return NewAnswerClient(_m.config).QueryQuestion(_m)
}

// QueryUser queries the "user" edge of the Answer entity.
func (_m *Answer) QueryUser() *UserQuery {
	return NewAnswerClient(_m.config).QueryUser(_m)
}

// Update returns a builder for updating this Answer.
// Note that you need to call Answer.Unwrap() before calling this method if this Answer
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Answer) Update() *AnswerUpdateOne {
	return NewAnswerClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Answer entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Answer) Unwrap() *Answer {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Answer is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Answer) String() string {
	var builder strings.Builder
	builder.WriteString("Answer(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("question_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.QuestionID))
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("answer_text=")
	builder.WriteString(_m.AnswerText)
	builder.WriteString(", ")
	builder.WriteString("submitted_at=")
	builder.WriteString(_m.SubmittedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Answers is a parsable slice of Answer.
type Answers []*Answer
