// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"su-organization-matching/server/ent/club"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// Club is the model entity for the Club schema.
type Club struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// ClubName holds the value of the "club_name" field.
	ClubName string `json:"club_name,omitempty"`
	// Description holds the value of the "description" field.
	Description string `json:"description,omitempty"`
	// MeetingTime holds the value of the "meeting_time" field.
	MeetingTime string `json:"meeting_time,omitempty"`
	// ImagePath holds the value of the "image_path" field.
	ImagePath string `json:"image_path,omitempty"`
	// ExternalLink holds the value of the "external_link" field.
	ExternalLink string `json:"external_link,omitempty"`
	// ContactInfo holds the value of the "contact_info" field.
	ContactInfo string `json:"contact_info,omitempty"`
	// IncludeOfficerEmails holds the value of the "include_officer_emails" field.
	IncludeOfficerEmails bool `json:"include_officer_emails,omitempty"`
	// Personality holds the value of the "personality" field.
	Personality []string `json:"personality,omitempty"`
	// Activities holds the value of the "activities" field.
	Activities []string `json:"activities,omitempty"`
	// Genders holds the value of the "genders" field.
	Genders []string `json:"genders,omitempty"`
	// Ethnicities holds the value of the "ethnicities" field.
	Ethnicities []string `json:"ethnicities,omitempty"`
	// Religions holds the value of the "religions" field.
	Religions []string `json:"religions,omitempty"`
	// StrictGenders holds the value of the "strict_genders" field.
	StrictGenders bool `json:"strict_genders,omitempty"`
	// DedicatedMajors holds the value of the "dedicated_majors" field.
	DedicatedMajors []string `json:"dedicated_majors,omitempty"`
	// AssociatedMajors holds the value of the "associated_majors" field.
	AssociatedMajors []string `json:"associated_majors,omitempty"`
	// Other holds the value of the "other" field.
	Other []string `json:"other,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ClubQuery when eager-loading is set.
	Edges        ClubEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ClubEdges holds the relations/edges for other nodes in the graph.
type ClubEdges struct {
	// Leaders holds the value of the leaders edge.
	Leaders []*User `json:"leaders,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// LeadersOrErr returns the Leaders value or an error if the edge
// was not loaded in eager-loading.
func (e ClubEdges) LeadersOrErr() ([]*User, error) {
	if e.loadedTypes[0] {
		return e.Leaders, nil
	}
	return nil, &NotLoadedError{edge: "leaders"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Club) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case club.FieldPersonality, club.FieldActivities, club.FieldGenders, club.FieldEthnicities, club.FieldReligions, club.FieldDedicatedMajors, club.FieldAssociatedMajors, club.FieldOther:
			values[i] = new([]byte)
		case club.FieldIncludeOfficerEmails, club.FieldStrictGenders:
			values[i] = new(sql.NullBool)
		case club.FieldID:
			values[i] = new(sql.NullInt64)
		case club.FieldClubName, club.FieldDescription, club.FieldMeetingTime, club.FieldImagePath, club.FieldExternalLink, club.FieldContactInfo:
			values[i] = new(sql.NullString)
		case club.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Club fields.
func (_m *Club) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case club.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case club.FieldClubName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field club_name", values[i])
			} else if value.Valid {
				_m.ClubName = value.String
			}
		case club.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				_m.Description = value.String
			}
		case club.FieldMeetingTime:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field meeting_time", values[i])
			} else if value.Valid {
				_m.MeetingTime = value.String
			}
		case club.FieldImagePath:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field image_path", values[i])
			} else if value.Valid {
				_m.ImagePath = value.String
			}
		case club.FieldExternalLink:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field external_link", values[i])
			} else if value.Valid {
				_m.ExternalLink = value.String
			}
		case club.FieldContactInfo:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field contact_info", values[i])
			} else if value.Valid {
				_m.ContactInfo = value.String
			}
		case club.FieldIncludeOfficerEmails:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field include_officer_emails", values[i])
			} else if value.Valid {
				_m.IncludeOfficerEmails = value.Bool
			}
		case club.FieldPersonality:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field personality", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Personality); err != nil {
					return fmt.Errorf("unmarshal field personality: %w", err)
				}
			}
		case club.FieldActivities:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field activities", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Activities); err != nil {
					return fmt.Errorf("unmarshal field activities: %w", err)
				}
			}
		case club.FieldGenders:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field genders", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Genders); err != nil {
					return fmt.Errorf("unmarshal field genders: %w", err)
				}
			}
		case club.FieldEthnicities:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field ethnicities", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Ethnicities); err != nil {
					return fmt.Errorf("unmarshal field ethnicities: %w", err)
				}
			}
		case club.FieldReligions:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field religions", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Religions); err != nil {
					return fmt.Errorf("unmarshal field religions: %w", err)
				}
			}
		case club.FieldStrictGenders:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field strict_genders", values[i])
			} else if value.Valid {
				_m.StrictGenders = value.Bool
			}
		case club.FieldDedicatedMajors:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field dedicated_majors", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.DedicatedMajors); err != nil {
					return fmt.Errorf("unmarshal field dedicated_majors: %w", err)
				}
			}
		case club.FieldAssociatedMajors:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field associated_majors", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.AssociatedMajors); err != nil {
					return fmt.Errorf("unmarshal field associated_majors: %w", err)
				}
			}
		case club.FieldOther:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field other", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Other); err != nil {
					return fmt.Errorf("unmarshal field other: %w", err)
				}
			}
		case club.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Club.
// This includes values selected through modifiers, order, etc.
func (_m *Club) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryLeaders queries the "leaders" edge of the Club entity.
func (_m *Club) QueryLeaders() *UserQuery {
	return NewClubClient(_m.config).QueryLeaders(_m)
}

// Update returns a builder for updating this Club.
// Note that you need to call Club.Unwrap() before calling this method if this Club
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Club) Update() *ClubUpdateOne {
	return NewClubClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Club entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Club) Unwrap() *Club {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Club is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Club) String() string {
	var builder strings.Builder
	builder.WriteString("Club(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("club_name=")
	builder.WriteString(_m.ClubName)
	builder.WriteString(", ")
	builder.WriteString("description=")
	builder.WriteString(_m.Description)
	builder.WriteString(", ")
	builder.WriteString("meeting_time=")
	builder.WriteString(_m.MeetingTime)
	builder.WriteString(", ")
	builder.WriteString("image_path=")
	builder.WriteString(_m.ImagePath)
	builder.WriteString(", ")
	builder.WriteString("external_link=")
	builder.WriteString(_m.ExternalLink)
	builder.WriteString(", ")
	builder.WriteString("contact_info=")
	builder.WriteString(_m.ContactInfo)
	builder.WriteString(", ")
	builder.WriteString("include_officer_emails=")
	builder.WriteString(fmt.Sprintf("%v", _m.IncludeOfficerEmails))
	builder.WriteString(", ")
	builder.WriteString("personality=")
	builder.WriteString(fmt.Sprintf("%v", _m.Personality))
	builder.WriteString(", ")
	builder.WriteString("activities=")
	builder.WriteString(fmt.Sprintf("%v", _m.Activities))
	builder.WriteString(", ")
	builder.WriteString("genders=")
	builder.WriteString(fmt.Sprintf("%v", _m.Genders))
	builder.WriteString(", ")
	builder.WriteString("ethnicities=")
	builder.WriteString(fmt.Sprintf("%v", _m.Ethnicities))
	builder.WriteString(", ")
	builder.WriteString("religions=")
	builder.WriteString(fmt.Sprintf("%v", _m.Religions))
	builder.WriteString(", ")
	builder.WriteString("strict_genders=")
	builder.WriteString(fmt.Sprintf("%v", _m.StrictGenders))
	builder.WriteString(", ")
	builder.WriteString("dedicated_majors=")
	builder.WriteString(fmt.Sprintf("%v", _m.DedicatedMajors))
	builder.WriteString(", ")
	builder.WriteString("associated_majors=")
	builder.WriteString(fmt.Sprintf("%v", _m.AssociatedMajors))
	builder.WriteString(", ")
	builder.WriteString("other=")
	builder.WriteString(fmt.Sprintf("%v", _m.Other))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Clubs is a parsable slice of Club.
type Clubs []*Club
