// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"server-example/ent/club"
	"server-example/ent/user"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ClubCreate is the builder for creating a Club entity.
type ClubCreate struct {
	config
	mutation *ClubMutation
	hooks    []Hook
}

// SetClubName sets the "club_name" field.
func (_c *ClubCreate) SetClubName(v string) *ClubCreate {
	_c.mutation.SetClubName(v)
	return _c
}

// SetDescription sets the "description" field.
func (_c *ClubCreate) SetDescription(v string) *ClubCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *ClubCreate) SetNillableDescription(v *string) *ClubCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetMeetingTime sets the "meeting_time" field.
func (_c *ClubCreate) SetMeetingTime(v string) *ClubCreate {
	_c.mutation.SetMeetingTime(v)
	return _c
}

// SetNillableMeetingTime sets the "meeting_time" field if the given value is not nil.
func (_c *ClubCreate) SetNillableMeetingTime(v *string) *ClubCreate {
	if v != nil {
		_c.SetMeetingTime(*v)
	}
	return _c
}

// SetImagePath sets the "image_path" field.
func (_c *ClubCreate) SetImagePath(v string) *ClubCreate {
	_c.mutation.SetImagePath(v)
	return _c
}

// SetNillableImagePath sets the "image_path" field if the given value is not nil.
func (_c *ClubCreate) SetNillableImagePath(v *string) *ClubCreate {
	if v != nil {
		_c.SetImagePath(*v)
	}
	return _c
}

// SetExternalLink sets the "external_link" field.
func (_c *ClubCreate) SetExternalLink(v string) *ClubCreate {
	_c.mutation.SetExternalLink(v)
	return _c
}

// SetNillableExternalLink sets the "external_link" field if the given value is not nil.
func (_c *ClubCreate) SetNillableExternalLink(v *string) *ClubCreate {
	if v != nil {
		_c.SetExternalLink(*v)
	}
	return _c
}

// SetContactInfo sets the "contact_info" field.
func (_c *ClubCreate) SetContactInfo(v string) *ClubCreate {
	_c.mutation.SetContactInfo(v)
	return _c
}

// SetNillableContactInfo sets the "contact_info" field if the given value is not nil.
func (_c *ClubCreate) SetNillableContactInfo(v *string) *ClubCreate {
	if v != nil {
		_c.SetContactInfo(*v)
	}
	return _c
}

// SetIncludeOfficerEmails sets the "include_officer_emails" field.
func (_c *ClubCreate) SetIncludeOfficerEmails(v bool) *ClubCreate {
	_c.mutation.SetIncludeOfficerEmails(v)
	return _c
}

// SetNillableIncludeOfficerEmails sets the "include_officer_emails" field if the given value is not nil.
func (_c *ClubCreate) SetNillableIncludeOfficerEmails(v *bool) *ClubCreate {
	if v != nil {
		_c.SetIncludeOfficerEmails(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ClubCreate) SetUpdatedAt(v time.Time) *ClubCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ClubCreate) SetNillableUpdatedAt(v *time.Time) *ClubCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// AddLeaderIDs adds the "leaders" edge to the User entity by IDs.
func (_c *ClubCreate) AddLeaderIDs(ids ...int) *ClubCreate {
	_c.mutation.AddLeaderIDs(ids...)
	return _c
}

// AddLeaders adds the "leaders" edges to the User entity.
func (_c *ClubCreate) AddLeaders(v ...*User) *ClubCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddLeaderIDs(ids...)
}

// Mutation returns the ClubMutation object of the builder.
func (_c *ClubCreate) Mutation() *ClubMutation {
	return _c.mutation
}

// Save creates the Club in the database.
func (_c *ClubCreate) Save(ctx context.Context) (*Club, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ClubCreate) SaveX(ctx context.Context) *Club {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ClubCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ClubCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ClubCreate) defaults() {
	if _, ok := _c.mutation.IncludeOfficerEmails(); !ok {
		v := club.DefaultIncludeOfficerEmails
		_c.mutation.SetIncludeOfficerEmails(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := club.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ClubCreate) check() error {
	if _, ok := _c.mutation.ClubName(); !ok {
		return &ValidationError{Name: "club_name", err: errors.New(`ent: missing required field "Club.club_name"`)}
	}
	if _, ok := _c.mutation.IncludeOfficerEmails(); !ok {
		return &ValidationError{Name: "include_officer_emails", err: errors.New(`ent: missing required field "Club.include_officer_emails"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Club.updated_at"`)}
	}
	return nil
}

func (_c *ClubCreate) sqlSave(ctx context.Context) (*Club, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ClubCreate) createSpec() (*Club, *sqlgraph.CreateSpec) {
	var (
		_node = &Club{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(club.Table, sqlgraph.NewFieldSpec(club.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.ClubName(); ok {
		_spec.SetField(club.FieldClubName, field.TypeString, value)
		_node.ClubName = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(club.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.MeetingTime(); ok {
		_spec.SetField(club.FieldMeetingTime, field.TypeString, value)
		_node.MeetingTime = value
	}
	if value, ok := _c.mutation.ImagePath(); ok {
		_spec.SetField(club.FieldImagePath, field.TypeString, value)
		_node.ImagePath = value
	}
	if value, ok := _c.mutation.ExternalLink(); ok {
		_spec.SetField(club.FieldExternalLink, field.TypeString, value)
		_node.ExternalLink = value
	}
	if value, ok := _c.mutation.ContactInfo(); ok {
		_spec.SetField(club.FieldContactInfo, field.TypeString, value)
		_node.ContactInfo = value
	}
	if value, ok := _c.mutation.IncludeOfficerEmails(); ok {
		_spec.SetField(club.FieldIncludeOfficerEmails, field.TypeBool, value)
		_node.IncludeOfficerEmails = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(club.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.LeadersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   club.LeadersTable,
			Columns: club.LeadersPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ClubCreateBulk is the builder for creating many Club entities in bulk.
type ClubCreateBulk struct {
	config
	err      error
	builders []*ClubCreate
}

// Save creates the Club entities in the database.
func (_c *ClubCreateBulk) Save(ctx context.Context) ([]*Club, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Club, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ClubMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ClubCreateBulk) SaveX(ctx context.Context) []*Club {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ClubCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ClubCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
