// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"su-organization-matching/server/ent/club"
	"su-organization-matching/server/ent/predicate"
	"su-organization-matching/server/ent/user"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ClubUpdate is the builder for updating Club entities.
type ClubUpdate struct {
	config
	hooks    []Hook
	mutation *ClubMutation
}

// Where appends a list predicates to the ClubUpdate builder.
func (_u *ClubUpdate) Where(ps ...predicate.Club) *ClubUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetClubName sets the "club_name" field.
func (_u *ClubUpdate) SetClubName(v string) *ClubUpdate {
	_u.mutation.SetClubName(v)
	return _u
}

// SetNillableClubName sets the "club_name" field if the given value is not nil.
func (_u *ClubUpdate) SetNillableClubName(v *string) *ClubUpdate {
	if v != nil {
		_u.SetClubName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *ClubUpdate) SetDescription(v string) *ClubUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *ClubUpdate) SetNillableDescription(v *string) *ClubUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *ClubUpdate) ClearDescription() *ClubUpdate {
	_u.mutation.ClearDescription()
	return _u
}

// SetMeetingTime sets the "meeting_time" field.
func (_u *ClubUpdate) SetMeetingTime(v string) *ClubUpdate {
	_u.mutation.SetMeetingTime(v)
	return _u
}

// SetNillableMeetingTime sets the "meeting_time" field if the given value is not nil.
func (_u *ClubUpdate) SetNillableMeetingTime(v *string) *ClubUpdate {
	if v != nil {
		_u.SetMeetingTime(*v)
	}
	return _u
}

// ClearMeetingTime clears the value of the "meeting_time" field.
func (_u *ClubUpdate) ClearMeetingTime() *ClubUpdate {
	_u.mutation.ClearMeetingTime()
	return _u
}

// SetImagePath sets the "image_path" field.
func (_u *ClubUpdate) SetImagePath(v string) *ClubUpdate {
	_u.mutation.SetImagePath(v)
	return _u
}

// SetNillableImagePath sets the "image_path" field if the given value is not nil.
func (_u *ClubUpdate) SetNillableImagePath(v *string) *ClubUpdate {
	if v != nil {
		_u.SetImagePath(*v)
	}
	return _u
}

// ClearImagePath clears the value of the "image_path" field.
func (_u *ClubUpdate) ClearImagePath() *ClubUpdate {
	_u.mutation.ClearImagePath()
	return _u
}

// SetExternalLink sets the "external_link" field.
func (_u *ClubUpdate) SetExternalLink(v string) *ClubUpdate {
	_u.mutation.SetExternalLink(v)
	return _u
}

// SetNillableExternalLink sets the "external_link" field if the given value is not nil.
func (_u *ClubUpdate) SetNillableExternalLink(v *string) *ClubUpdate {
	if v != nil {
		_u.SetExternalLink(*v)
	}
	return _u
}

// ClearExternalLink clears the value of the "external_link" field.
func (_u *ClubUpdate) ClearExternalLink() *ClubUpdate {
	_u.mutation.ClearExternalLink()
	return _u
}

// SetContactInfo sets the "contact_info" field.
func (_u *ClubUpdate) SetContactInfo(v string) *ClubUpdate {
	_u.mutation.SetContactInfo(v)
	return _u
}

// SetNillableContactInfo sets the "contact_info" field if the given value is not nil.
func (_u *ClubUpdate) SetNillableContactInfo(v *string) *ClubUpdate {
	if v != nil {
		_u.SetContactInfo(*v)
	}
	return _u
}

// ClearContactInfo clears the value of the "contact_info" field.
func (_u *ClubUpdate) ClearContactInfo() *ClubUpdate {
	_u.mutation.ClearContactInfo()
	return _u
}

// SetIncludeOfficerEmails sets the "include_officer_emails" field.
func (_u *ClubUpdate) SetIncludeOfficerEmails(v bool) *ClubUpdate {
	_u.mutation.SetIncludeOfficerEmails(v)
	return _u
}

// SetNillableIncludeOfficerEmails sets the "include_officer_emails" field if the given value is not nil.
func (_u *ClubUpdate) SetNillableIncludeOfficerEmails(v *bool) *ClubUpdate {
	if v != nil {
		_u.SetIncludeOfficerEmails(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ClubUpdate) SetUpdatedAt(v time.Time) *ClubUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddLeaderIDs adds the "leaders" edge to the User entity by IDs.
func (_u *ClubUpdate) AddLeaderIDs(ids ...int) *ClubUpdate {
	_u.mutation.AddLeaderIDs(ids...)
	return _u
}

// AddLeaders adds the "leaders" edges to the User entity.
func (_u *ClubUpdate) AddLeaders(v ...*User) *ClubUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddLeaderIDs(ids...)
}

// Mutation returns the ClubMutation object of the builder.
func (_u *ClubUpdate) Mutation() *ClubMutation {
	return _u.mutation
}

// ClearLeaders clears all "leaders" edges to the User entity.
func (_u *ClubUpdate) ClearLeaders() *ClubUpdate {
	_u.mutation.ClearLeaders()
	return _u
}

// RemoveLeaderIDs removes the "leaders" edge to User entities by IDs.
func (_u *ClubUpdate) RemoveLeaderIDs(ids ...int) *ClubUpdate {
	_u.mutation.RemoveLeaderIDs(ids...)
	return _u
}

// RemoveLeaders removes "leaders" edges to User entities.
func (_u *ClubUpdate) RemoveLeaders(v ...*User) *ClubUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveLeaderIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ClubUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ClubUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ClubUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ClubUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ClubUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := club.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *ClubUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(club.Table, club.Columns, sqlgraph.NewFieldSpec(club.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ClubName(); ok {
		_spec.SetField(club.FieldClubName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(club.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(club.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.MeetingTime(); ok {
		_spec.SetField(club.FieldMeetingTime, field.TypeString, value)
	}
	if _u.mutation.MeetingTimeCleared() {
		_spec.ClearField(club.FieldMeetingTime, field.TypeString)
	}
	if value, ok := _u.mutation.ImagePath(); ok {
		_spec.SetField(club.FieldImagePath, field.TypeString, value)
	}
	if _u.mutation.ImagePathCleared() {
		_spec.ClearField(club.FieldImagePath, field.TypeString)
	}
	if value, ok := _u.mutation.ExternalLink(); ok {
		_spec.SetField(club.FieldExternalLink, field.TypeString, value)
	}
	if _u.mutation.ExternalLinkCleared() {
		_spec.ClearField(club.FieldExternalLink, field.TypeString)
	}
	if value, ok := _u.mutation.ContactInfo(); ok {
		_spec.SetField(club.FieldContactInfo, field.TypeString, value)
	}
	if _u.mutation.ContactInfoCleared() {
		_spec.ClearField(club.FieldContactInfo, field.TypeString)
	}
	if value, ok := _u.mutation.IncludeOfficerEmails(); ok {
		_spec.SetField(club.FieldIncludeOfficerEmails, field.TypeBool, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(club.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.LeadersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   club.LeadersTable,
			Columns: club.LeadersPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedLeadersIDs(); len(nodes) > 0 && !_u.mutation.LeadersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   club.LeadersTable,
			Columns: club.LeadersPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.LeadersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   club.LeadersTable,
			Columns: club.LeadersPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{club.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ClubUpdateOne is the builder for updating a single Club entity.
type ClubUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ClubMutation
}

// SetClubName sets the "club_name" field.
func (_u *ClubUpdateOne) SetClubName(v string) *ClubUpdateOne {
	_u.mutation.SetClubName(v)
	return _u
}

// SetNillableClubName sets the "club_name" field if the given value is not nil.
func (_u *ClubUpdateOne) SetNillableClubName(v *string) *ClubUpdateOne {
	if v != nil {
		_u.SetClubName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *ClubUpdateOne) SetDescription(v string) *ClubUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *ClubUpdateOne) SetNillableDescription(v *string) *ClubUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *ClubUpdateOne) ClearDescription() *ClubUpdateOne {
	_u.mutation.ClearDescription()
	return _u
}

// SetMeetingTime sets the "meeting_time" field.
func (_u *ClubUpdateOne) SetMeetingTime(v string) *ClubUpdateOne {
	_u.mutation.SetMeetingTime(v)
	return _u
}

// SetNillableMeetingTime sets the "meeting_time" field if the given value is not nil.
func (_u *ClubUpdateOne) SetNillableMeetingTime(v *string) *ClubUpdateOne {
	if v != nil {
		_u.SetMeetingTime(*v)
	}
	return _u
}

// ClearMeetingTime clears the value of the "meeting_time" field.
func (_u *ClubUpdateOne) ClearMeetingTime() *ClubUpdateOne {
	_u.mutation.ClearMeetingTime()
	return _u
}

// SetImagePath sets the "image_path" field.
func (_u *ClubUpdateOne) SetImagePath(v string) *ClubUpdateOne {
	_u.mutation.SetImagePath(v)
	return _u
}

// SetNillableImagePath sets the "image_path" field if the given value is not nil.
func (_u *ClubUpdateOne) SetNillableImagePath(v *string) *ClubUpdateOne {
	if v != nil {
		_u.SetImagePath(*v)
	}
	return _u
}

// ClearImagePath clears the value of the "image_path" field.
func (_u *ClubUpdateOne) ClearImagePath() *ClubUpdateOne {
	_u.mutation.ClearImagePath()
	return _u
}

// SetExternalLink sets the "external_link" field.
func (_u *ClubUpdateOne) SetExternalLink(v string) *ClubUpdateOne {
	_u.mutation.SetExternalLink(v)
	return _u
}

// SetNillableExternalLink sets the "external_link" field if the given value is not nil.
func (_u *ClubUpdateOne) SetNillableExternalLink(v *string) *ClubUpdateOne {
	if v != nil {
		_u.SetExternalLink(*v)
	}
	return _u
}

// ClearExternalLink clears the value of the "external_link" field.
func (_u *ClubUpdateOne) ClearExternalLink() *ClubUpdateOne {
	_u.mutation.ClearExternalLink()
	return _u
}

// SetContactInfo sets the "contact_info" field.
func (_u *ClubUpdateOne) SetContactInfo(v string) *ClubUpdateOne {
	_u.mutation.SetContactInfo(v)
	return _u
}

// SetNillableContactInfo sets the "contact_info" field if the given value is not nil.
func (_u *ClubUpdateOne) SetNillableContactInfo(v *string) *ClubUpdateOne {
	if v != nil {
		_u.SetContactInfo(*v)
	}
	return _u
}

// ClearContactInfo clears the value of the "contact_info" field.
func (_u *ClubUpdateOne) ClearContactInfo() *ClubUpdateOne {
	_u.mutation.ClearContactInfo()
	return _u
}

// SetIncludeOfficerEmails sets the "include_officer_emails" field.
func (_u *ClubUpdateOne) SetIncludeOfficerEmails(v bool) *ClubUpdateOne {
	_u.mutation.SetIncludeOfficerEmails(v)
	return _u
}

// SetNillableIncludeOfficerEmails sets the "include_officer_emails" field if the given value is not nil.
func (_u *ClubUpdateOne) SetNillableIncludeOfficerEmails(v *bool) *ClubUpdateOne {
	if v != nil {
		_u.SetIncludeOfficerEmails(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ClubUpdateOne) SetUpdatedAt(v time.Time) *ClubUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddLeaderIDs adds the "leaders" edge to the User entity by IDs.
func (_u *ClubUpdateOne) AddLeaderIDs(ids ...int) *ClubUpdateOne {
	_u.mutation.AddLeaderIDs(ids...)
	return _u
}

// AddLeaders adds the "leaders" edges to the User entity.
func (_u *ClubUpdateOne) AddLeaders(v ...*User) *ClubUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddLeaderIDs(ids...)
}

// Mutation returns the ClubMutation object of the builder.
func (_u *ClubUpdateOne) Mutation() *ClubMutation {
	return _u.mutation
}

// ClearLeaders clears all "leaders" edges to the User entity.
func (_u *ClubUpdateOne) ClearLeaders() *ClubUpdateOne {
	_u.mutation.ClearLeaders()
	return _u
}

// RemoveLeaderIDs removes the "leaders" edge to User entities by IDs.
func (_u *ClubUpdateOne) RemoveLeaderIDs(ids ...int) *ClubUpdateOne {
	_u.mutation.RemoveLeaderIDs(ids...)
	return _u
}

// RemoveLeaders removes "leaders" edges to User entities.
func (_u *ClubUpdateOne) RemoveLeaders(v ...*User) *ClubUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveLeaderIDs(ids...)
}

// Where appends a list predicates to the ClubUpdate builder.
func (_u *ClubUpdateOne) Where(ps ...predicate.Club) *ClubUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ClubUpdateOne) Select(field string, fields ...string) *ClubUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Club entity.
func (_u *ClubUpdateOne) Save(ctx context.Context) (*Club, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ClubUpdateOne) SaveX(ctx context.Context) *Club {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ClubUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ClubUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ClubUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := club.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *ClubUpdateOne) sqlSave(ctx context.Context) (_node *Club, err error) {
	_spec := sqlgraph.NewUpdateSpec(club.Table, club.Columns, sqlgraph.NewFieldSpec(club.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Club.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, club.FieldID)
		for _, f := range fields {
			if !club.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != club.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ClubName(); ok {
		_spec.SetField(club.FieldClubName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(club.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(club.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.MeetingTime(); ok {
		_spec.SetField(club.FieldMeetingTime, field.TypeString, value)
	}
	if _u.mutation.MeetingTimeCleared() {
		_spec.ClearField(club.FieldMeetingTime, field.TypeString)
	}
	if value, ok := _u.mutation.ImagePath(); ok {
		_spec.SetField(club.FieldImagePath, field.TypeString, value)
	}
	if _u.mutation.ImagePathCleared() {
		_spec.ClearField(club.FieldImagePath, field.TypeString)
	}
	if value, ok := _u.mutation.ExternalLink(); ok {
		_spec.SetField(club.FieldExternalLink, field.TypeString, value)
	}
	if _u.mutation.ExternalLinkCleared() {
		_spec.ClearField(club.FieldExternalLink, field.TypeString)
	}
	if value, ok := _u.mutation.ContactInfo(); ok {
		_spec.SetField(club.FieldContactInfo, field.TypeString, value)
	}
	if _u.mutation.ContactInfoCleared() {
		_spec.ClearField(club.FieldContactInfo, field.TypeString)
	}
	if value, ok := _u.mutation.IncludeOfficerEmails(); ok {
		_spec.SetField(club.FieldIncludeOfficerEmails, field.TypeBool, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(club.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.LeadersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   club.LeadersTable,
			Columns: club.LeadersPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedLeadersIDs(); len(nodes) > 0 && !_u.mutation.LeadersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   club.LeadersTable,
			Columns: club.LeadersPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.LeadersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   club.LeadersTable,
			Columns: club.LeadersPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Club{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{club.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
