// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"su-organization-matching/server/ent/answer"
	"su-organization-matching/server/ent/predicate"
	"su-organization-matching/server/ent/question"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// QuestionUpdate is the builder for updating Question entities.
type QuestionUpdate struct {
	config
	hooks    []Hook
	mutation *QuestionMutation
}

// Where appends a list predicates to the QuestionUpdate builder.
func (_u *QuestionUpdate) Where(ps ...predicate.Question) *QuestionUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetQuestionType sets the "question_type" field.
func (_u *QuestionUpdate) SetQuestionType(v string) *QuestionUpdate {
	_u.mutation.SetQuestionType(v)
	return _u
}

// SetNillableQuestionType sets the "question_type" field if the given value is not nil.
func (_u *QuestionUpdate) SetNillableQuestionType(v *string) *QuestionUpdate {
	if v != nil {
		_u.SetQuestionType(*v)
	}
	return _u
}

// SetTranslations sets the "translations" field.
func (_u *QuestionUpdate) SetTranslations(v map[string][]string) *QuestionUpdate {
	_u.mutation.SetTranslations(v)
	return _u
}

// SetIsActive sets the "is_active" field.
func (_u *QuestionUpdate) SetIsActive(v bool) *QuestionUpdate {
	_u.mutation.SetIsActive(v)
	return _u
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (_u *QuestionUpdate) SetNillableIsActive(v *bool) *QuestionUpdate {
	if v != nil {
		_u.SetIsActive(*v)
	}
	return _u
}

// AddAnswerIDs adds the "answers" edge to the Answer entity by IDs.
func (_u *QuestionUpdate) AddAnswerIDs(ids ...int) *QuestionUpdate {
	_u.mutation.AddAnswerIDs(ids...)
	return _u
}

// AddAnswers adds the "answers" edges to the Answer entity.
func (_u *QuestionUpdate) AddAnswers(v ...*Answer) *QuestionUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAnswerIDs(ids...)
}

// Mutation returns the QuestionMutation object of the builder.
func (_u *QuestionUpdate) Mutation() *QuestionMutation {
	return _u.mutation
}

// ClearAnswers clears all "answers" edges to the Answer entity.
func (_u *QuestionUpdate) ClearAnswers() *QuestionUpdate {
	_u.mutation.ClearAnswers()
	return _u
}

// RemoveAnswerIDs removes the "answers" edge to Answer entities by IDs.
func (_u *QuestionUpdate) RemoveAnswerIDs(ids ...int) *QuestionUpdate {
	_u.mutation.RemoveAnswerIDs(ids...)
	return _u
}

// RemoveAnswers removes "answers" edges to Answer entities.
func (_u *QuestionUpdate) RemoveAnswers(v ...*Answer) *QuestionUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAnswerIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *QuestionUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *QuestionUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *QuestionUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *QuestionUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *QuestionUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(question.Table, question.Columns, sqlgraph.NewFieldSpec(question.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.QuestionType(); ok {
		_spec.SetField(question.FieldQuestionType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Translations(); ok {
		_spec.SetField(question.FieldTranslations, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.IsActive(); ok {
		_spec.SetField(question.FieldIsActive, field.TypeBool, value)
	}
	if _u.mutation.AnswersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   question.AnswersTable,
			Columns: []string{question.AnswersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(answer.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAnswersIDs(); len(nodes) > 0 && !_u.mutation.AnswersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   question.AnswersTable,
			Columns: []string{question.AnswersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(answer.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AnswersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   question.AnswersTable,
			Columns: []string{question.AnswersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(answer.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{question.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// QuestionUpdateOne is the builder for updating a single Question entity.
type QuestionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *QuestionMutation
}

// SetQuestionType sets the "question_type" field.
func (_u *QuestionUpdateOne) SetQuestionType(v string) *QuestionUpdateOne {
	_u.mutation.SetQuestionType(v)
	return _u
}

// SetNillableQuestionType sets the "question_type" field if the given value is not nil.
func (_u *QuestionUpdateOne) SetNillableQuestionType(v *string) *QuestionUpdateOne {
	if v != nil {
		_u.SetQuestionType(*v)
	}
	return _u
}

// SetTranslations sets the "translations" field.
func (_u *QuestionUpdateOne) SetTranslations(v map[string][]string) *QuestionUpdateOne {
	_u.mutation.SetTranslations(v)
	return _u
}

// SetIsActive sets the "is_active" field.
func (_u *QuestionUpdateOne) SetIsActive(v bool) *QuestionUpdateOne {
	_u.mutation.SetIsActive(v)
	return _u
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (_u *QuestionUpdateOne) SetNillableIsActive(v *bool) *QuestionUpdateOne {
	if v != nil {
		_u.SetIsActive(*v)
	}
	return _u
}

// AddAnswerIDs adds the "answers" edge to the Answer entity by IDs.
func (_u *QuestionUpdateOne) AddAnswerIDs(ids ...int) *QuestionUpdateOne {
	_u.mutation.AddAnswerIDs(ids...)
	return _u
}

// AddAnswers adds the "answers" edges to the Answer entity.
func (_u *QuestionUpdateOne) AddAnswers(v ...*Answer) *QuestionUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAnswerIDs(ids...)
}

// Mutation returns the QuestionMutation object of the builder.
func (_u *QuestionUpdateOne) Mutation() *QuestionMutation {
	return _u.mutation
}

// ClearAnswers clears all "answers" edges to the Answer entity.
func (_u *QuestionUpdateOne) ClearAnswers() *QuestionUpdateOne {
	_u.mutation.ClearAnswers()
	return _u
}

// RemoveAnswerIDs removes the "answers" edge to Answer entities by IDs.
func (_u *QuestionUpdateOne) RemoveAnswerIDs(ids ...int) *QuestionUpdateOne {
	_u.mutation.RemoveAnswerIDs(ids...)
	return _u
}

// RemoveAnswers removes "answers" edges to Answer entities.
func (_u *QuestionUpdateOne) RemoveAnswers(v ...*Answer) *QuestionUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAnswerIDs(ids...)
}

// Where appends a list predicates to the QuestionUpdate builder.
func (_u *QuestionUpdateOne) Where(ps ...predicate.Question) *QuestionUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *QuestionUpdateOne) Select(field string, fields ...string) *QuestionUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Question entity.
func (_u *QuestionUpdateOne) Save(ctx context.Context) (*Question, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *QuestionUpdateOne) SaveX(ctx context.Context) *Question {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *QuestionUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *QuestionUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *QuestionUpdateOne) sqlSave(ctx context.Context) (_node *Question, err error) {
	_spec := sqlgraph.NewUpdateSpec(question.Table, question.Columns, sqlgraph.NewFieldSpec(question.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Question.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, question.FieldID)
		for _, f := range fields {
			if !question.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != question.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.QuestionType(); ok {
		_spec.SetField(question.FieldQuestionType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Translations(); ok {
		_spec.SetField(question.FieldTranslations, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.IsActive(); ok {
		_spec.SetField(question.FieldIsActive, field.TypeBool, value)
	}
	if _u.mutation.AnswersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   question.AnswersTable,
			Columns: []string{question.AnswersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(answer.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAnswersIDs(); len(nodes) > 0 && !_u.mutation.AnswersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   question.AnswersTable,
			Columns: []string{question.AnswersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(answer.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AnswersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   question.AnswersTable,
			Columns: []string{question.AnswersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(answer.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Question{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{question.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
