// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"server-example/ent/answer"
	"server-example/ent/club"
	"server-example/ent/predicate"
	"server-example/ent/user"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
)

// UserUpdate is the builder for updating User entities.
type UserUpdate struct {
	config
	hooks    []Hook
	mutation *UserMutation
}

// Where appends a list predicates to the UserUpdate builder.
func (_u *UserUpdate) Where(ps ...predicate.User) *UserUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetGoogleID sets the "google_id" field.
func (_u *UserUpdate) SetGoogleID(v string) *UserUpdate {
	_u.mutation.SetGoogleID(v)
	return _u
}

// SetNillableGoogleID sets the "google_id" field if the given value is not nil.
func (_u *UserUpdate) SetNillableGoogleID(v *string) *UserUpdate {
	if v != nil {
		_u.SetGoogleID(*v)
	}
	return _u
}

// SetEmail sets the "email" field.
func (_u *UserUpdate) SetEmail(v string) *UserUpdate {
	_u.mutation.SetEmail(v)
	return _u
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_u *UserUpdate) SetNillableEmail(v *string) *UserUpdate {
	if v != nil {
		_u.SetEmail(*v)
	}
	return _u
}

// SetTags sets the "tags" field.
func (_u *UserUpdate) SetTags(v []string) *UserUpdate {
	_u.mutation.SetTags(v)
	return _u
}

// AppendTags appends value to the "tags" field.
func (_u *UserUpdate) AppendTags(v []string) *UserUpdate {
	_u.mutation.AppendTags(v)
	return _u
}

// SetGenders sets the "genders" field.
func (_u *UserUpdate) SetGenders(v []string) *UserUpdate {
	_u.mutation.SetGenders(v)
	return _u
}

// AppendGenders appends value to the "genders" field.
func (_u *UserUpdate) AppendGenders(v []string) *UserUpdate {
	_u.mutation.AppendGenders(v)
	return _u
}

// SetEthnicities sets the "ethnicities" field.
func (_u *UserUpdate) SetEthnicities(v []string) *UserUpdate {
	_u.mutation.SetEthnicities(v)
	return _u
}

// AppendEthnicities appends value to the "ethnicities" field.
func (_u *UserUpdate) AppendEthnicities(v []string) *UserUpdate {
	_u.mutation.AppendEthnicities(v)
	return _u
}

// SetReligions sets the "religions" field.
func (_u *UserUpdate) SetReligions(v []string) *UserUpdate {
	_u.mutation.SetReligions(v)
	return _u
}

// AppendReligions appends value to the "religions" field.
func (_u *UserUpdate) AppendReligions(v []string) *UserUpdate {
	_u.mutation.AppendReligions(v)
	return _u
}

// SetDedicatedMajors sets the "dedicated_majors" field.
func (_u *UserUpdate) SetDedicatedMajors(v []string) *UserUpdate {
	_u.mutation.SetDedicatedMajors(v)
	return _u
}

// AppendDedicatedMajors appends value to the "dedicated_majors" field.
func (_u *UserUpdate) AppendDedicatedMajors(v []string) *UserUpdate {
	_u.mutation.AppendDedicatedMajors(v)
	return _u
}

// SetOther sets the "other" field.
func (_u *UserUpdate) SetOther(v []string) *UserUpdate {
	_u.mutation.SetOther(v)
	return _u
}

// AppendOther appends value to the "other" field.
func (_u *UserUpdate) AppendOther(v []string) *UserUpdate {
	_u.mutation.AppendOther(v)
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *UserUpdate) SetCreatedAt(v time.Time) *UserUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *UserUpdate) SetNillableCreatedAt(v *time.Time) *UserUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// AddLedClubIDs adds the "led_clubs" edge to the Club entity by IDs.
func (_u *UserUpdate) AddLedClubIDs(ids ...int) *UserUpdate {
	_u.mutation.AddLedClubIDs(ids...)
	return _u
}

// AddLedClubs adds the "led_clubs" edges to the Club entity.
func (_u *UserUpdate) AddLedClubs(v ...*Club) *UserUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddLedClubIDs(ids...)
}

// AddAnswerIDs adds the "answers" edge to the Answer entity by IDs.
func (_u *UserUpdate) AddAnswerIDs(ids ...int) *UserUpdate {
	_u.mutation.AddAnswerIDs(ids...)
	return _u
}

// AddAnswers adds the "answers" edges to the Answer entity.
func (_u *UserUpdate) AddAnswers(v ...*Answer) *UserUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAnswerIDs(ids...)
}

// Mutation returns the UserMutation object of the builder.
func (_u *UserUpdate) Mutation() *UserMutation {
	return _u.mutation
}

// ClearLedClubs clears all "led_clubs" edges to the Club entity.
func (_u *UserUpdate) ClearLedClubs() *UserUpdate {
	_u.mutation.ClearLedClubs()
	return _u
}

// RemoveLedClubIDs removes the "led_clubs" edge to Club entities by IDs.
func (_u *UserUpdate) RemoveLedClubIDs(ids ...int) *UserUpdate {
	_u.mutation.RemoveLedClubIDs(ids...)
	return _u
}

// RemoveLedClubs removes "led_clubs" edges to Club entities.
func (_u *UserUpdate) RemoveLedClubs(v ...*Club) *UserUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveLedClubIDs(ids...)
}

// ClearAnswers clears all "answers" edges to the Answer entity.
func (_u *UserUpdate) ClearAnswers() *UserUpdate {
	_u.mutation.ClearAnswers()
	return _u
}

// RemoveAnswerIDs removes the "answers" edge to Answer entities by IDs.
func (_u *UserUpdate) RemoveAnswerIDs(ids ...int) *UserUpdate {
	_u.mutation.RemoveAnswerIDs(ids...)
	return _u
}

// RemoveAnswers removes "answers" edges to Answer entities.
func (_u *UserUpdate) RemoveAnswers(v ...*Answer) *UserUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAnswerIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *UserUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *UserUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *UserUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(user.Table, user.Columns, sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.GoogleID(); ok {
		_spec.SetField(user.FieldGoogleID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Email(); ok {
		_spec.SetField(user.FieldEmail, field.TypeString, value)
	}
	if value, ok := _u.mutation.Tags(); ok {
		_spec.SetField(user.FieldTags, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedTags(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, user.FieldTags, value)
		})
	}
	if value, ok := _u.mutation.Genders(); ok {
		_spec.SetField(user.FieldGenders, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedGenders(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, user.FieldGenders, value)
		})
	}
	if value, ok := _u.mutation.Ethnicities(); ok {
		_spec.SetField(user.FieldEthnicities, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedEthnicities(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, user.FieldEthnicities, value)
		})
	}
	if value, ok := _u.mutation.Religions(); ok {
		_spec.SetField(user.FieldReligions, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedReligions(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, user.FieldReligions, value)
		})
	}
	if value, ok := _u.mutation.DedicatedMajors(); ok {
		_spec.SetField(user.FieldDedicatedMajors, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedDedicatedMajors(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, user.FieldDedicatedMajors, value)
		})
	}
	if value, ok := _u.mutation.Other(); ok {
		_spec.SetField(user.FieldOther, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedOther(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, user.FieldOther, value)
		})
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(user.FieldCreatedAt, field.TypeTime, value)
	}
	if _u.mutation.LedClubsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   user.LedClubsTable,
			Columns: user.LedClubsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(club.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedLedClubsIDs(); len(nodes) > 0 && !_u.mutation.LedClubsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   user.LedClubsTable,
			Columns: user.LedClubsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(club.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.LedClubsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   user.LedClubsTable,
			Columns: user.LedClubsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(club.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AnswersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.AnswersTable,
			Columns: []string{user.AnswersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(answer.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAnswersIDs(); len(nodes) > 0 && !_u.mutation.AnswersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.AnswersTable,
			Columns: []string{user.AnswersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(answer.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AnswersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.AnswersTable,
			Columns: []string{user.AnswersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(answer.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{user.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// UserUpdateOne is the builder for updating a single User entity.
type UserUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UserMutation
}

// SetGoogleID sets the "google_id" field.
func (_u *UserUpdateOne) SetGoogleID(v string) *UserUpdateOne {
	_u.mutation.SetGoogleID(v)
	return _u
}

// SetNillableGoogleID sets the "google_id" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableGoogleID(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetGoogleID(*v)
	}
	return _u
}

// SetEmail sets the "email" field.
func (_u *UserUpdateOne) SetEmail(v string) *UserUpdateOne {
	_u.mutation.SetEmail(v)
	return _u
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableEmail(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetEmail(*v)
	}
	return _u
}

// SetTags sets the "tags" field.
func (_u *UserUpdateOne) SetTags(v []string) *UserUpdateOne {
	_u.mutation.SetTags(v)
	return _u
}

// AppendTags appends value to the "tags" field.
func (_u *UserUpdateOne) AppendTags(v []string) *UserUpdateOne {
	_u.mutation.AppendTags(v)
	return _u
}

// SetGenders sets the "genders" field.
func (_u *UserUpdateOne) SetGenders(v []string) *UserUpdateOne {
	_u.mutation.SetGenders(v)
	return _u
}

// AppendGenders appends value to the "genders" field.
func (_u *UserUpdateOne) AppendGenders(v []string) *UserUpdateOne {
	_u.mutation.AppendGenders(v)
	return _u
}

// SetEthnicities sets the "ethnicities" field.
func (_u *UserUpdateOne) SetEthnicities(v []string) *UserUpdateOne {
	_u.mutation.SetEthnicities(v)
	return _u
}

// AppendEthnicities appends value to the "ethnicities" field.
func (_u *UserUpdateOne) AppendEthnicities(v []string) *UserUpdateOne {
	_u.mutation.AppendEthnicities(v)
	return _u
}

// SetReligions sets the "religions" field.
func (_u *UserUpdateOne) SetReligions(v []string) *UserUpdateOne {
	_u.mutation.SetReligions(v)
	return _u
}

// AppendReligions appends value to the "religions" field.
func (_u *UserUpdateOne) AppendReligions(v []string) *UserUpdateOne {
	_u.mutation.AppendReligions(v)
	return _u
}

// SetDedicatedMajors sets the "dedicated_majors" field.
func (_u *UserUpdateOne) SetDedicatedMajors(v []string) *UserUpdateOne {
	_u.mutation.SetDedicatedMajors(v)
	return _u
}

// AppendDedicatedMajors appends value to the "dedicated_majors" field.
func (_u *UserUpdateOne) AppendDedicatedMajors(v []string) *UserUpdateOne {
	_u.mutation.AppendDedicatedMajors(v)
	return _u
}

// SetOther sets the "other" field.
func (_u *UserUpdateOne) SetOther(v []string) *UserUpdateOne {
	_u.mutation.SetOther(v)
	return _u
}

// AppendOther appends value to the "other" field.
func (_u *UserUpdateOne) AppendOther(v []string) *UserUpdateOne {
	_u.mutation.AppendOther(v)
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *UserUpdateOne) SetCreatedAt(v time.Time) *UserUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableCreatedAt(v *time.Time) *UserUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// AddLedClubIDs adds the "led_clubs" edge to the Club entity by IDs.
func (_u *UserUpdateOne) AddLedClubIDs(ids ...int) *UserUpdateOne {
	_u.mutation.AddLedClubIDs(ids...)
	return _u
}

// AddLedClubs adds the "led_clubs" edges to the Club entity.
func (_u *UserUpdateOne) AddLedClubs(v ...*Club) *UserUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddLedClubIDs(ids...)
}

// AddAnswerIDs adds the "answers" edge to the Answer entity by IDs.
func (_u *UserUpdateOne) AddAnswerIDs(ids ...int) *UserUpdateOne {
	_u.mutation.AddAnswerIDs(ids...)
	return _u
}

// AddAnswers adds the "answers" edges to the Answer entity.
func (_u *UserUpdateOne) AddAnswers(v ...*Answer) *UserUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAnswerIDs(ids...)
}

// Mutation returns the UserMutation object of the builder.
func (_u *UserUpdateOne) Mutation() *UserMutation {
	return _u.mutation
}

// ClearLedClubs clears all "led_clubs" edges to the Club entity.
func (_u *UserUpdateOne) ClearLedClubs() *UserUpdateOne {
	_u.mutation.ClearLedClubs()
	return _u
}

// RemoveLedClubIDs removes the "led_clubs" edge to Club entities by IDs.
func (_u *UserUpdateOne) RemoveLedClubIDs(ids ...int) *UserUpdateOne {
	_u.mutation.RemoveLedClubIDs(ids...)
	return _u
}

// RemoveLedClubs removes "led_clubs" edges to Club entities.
func (_u *UserUpdateOne) RemoveLedClubs(v ...*Club) *UserUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveLedClubIDs(ids...)
}

// ClearAnswers clears all "answers" edges to the Answer entity.
func (_u *UserUpdateOne) ClearAnswers() *UserUpdateOne {
	_u.mutation.ClearAnswers()
	return _u
}

// RemoveAnswerIDs removes the "answers" edge to Answer entities by IDs.
func (_u *UserUpdateOne) RemoveAnswerIDs(ids ...int) *UserUpdateOne {
	_u.mutation.RemoveAnswerIDs(ids...)
	return _u
}

// RemoveAnswers removes "answers" edges to Answer entities.
func (_u *UserUpdateOne) RemoveAnswers(v ...*Answer) *UserUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAnswerIDs(ids...)
}

// Where appends a list predicates to the UserUpdate builder.
func (_u *UserUpdateOne) Where(ps ...predicate.User) *UserUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *UserUpdateOne) Select(field string, fields ...string) *UserUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated User entity.
func (_u *UserUpdateOne) Save(ctx context.Context) (*User, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserUpdateOne) SaveX(ctx context.Context) *User {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *UserUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *UserUpdateOne) sqlSave(ctx context.Context) (_node *User, err error) {
	_spec := sqlgraph.NewUpdateSpec(user.Table, user.Columns, sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "User.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, user.FieldID)
		for _, f := range fields {
			if !user.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != user.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.GoogleID(); ok {
		_spec.SetField(user.FieldGoogleID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Email(); ok {
		_spec.SetField(user.FieldEmail, field.TypeString, value)
	}
	if value, ok := _u.mutation.Tags(); ok {
		_spec.SetField(user.FieldTags, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedTags(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, user.FieldTags, value)
		})
	}
	if value, ok := _u.mutation.Genders(); ok {
		_spec.SetField(user.FieldGenders, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedGenders(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, user.FieldGenders, value)
		})
	}
	if value, ok := _u.mutation.Ethnicities(); ok {
		_spec.SetField(user.FieldEthnicities, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedEthnicities(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, user.FieldEthnicities, value)
		})
	}
	if value, ok := _u.mutation.Religions(); ok {
		_spec.SetField(user.FieldReligions, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedReligions(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, user.FieldReligions, value)
		})
	}
	if value, ok := _u.mutation.DedicatedMajors(); ok {
		_spec.SetField(user.FieldDedicatedMajors, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedDedicatedMajors(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, user.FieldDedicatedMajors, value)
		})
	}
	if value, ok := _u.mutation.Other(); ok {
		_spec.SetField(user.FieldOther, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedOther(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, user.FieldOther, value)
		})
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(user.FieldCreatedAt, field.TypeTime, value)
	}
	if _u.mutation.LedClubsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   user.LedClubsTable,
			Columns: user.LedClubsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(club.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedLedClubsIDs(); len(nodes) > 0 && !_u.mutation.LedClubsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   user.LedClubsTable,
			Columns: user.LedClubsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(club.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.LedClubsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   user.LedClubsTable,
			Columns: user.LedClubsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(club.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AnswersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.AnswersTable,
			Columns: []string{user.AnswersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(answer.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAnswersIDs(); len(nodes) > 0 && !_u.mutation.AnswersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.AnswersTable,
			Columns: []string{user.AnswersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(answer.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AnswersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.AnswersTable,
			Columns: []string{user.AnswersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(answer.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &User{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{user.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
