// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"su-organization-matching/server/ent/user"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// User is the model entity for the User schema.
type User struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// GoogleID holds the value of the "google_id" field.
	GoogleID string `json:"google_id,omitempty"`
	// Email holds the value of the "email" field.
	Email string `json:"email,omitempty"`
	// Tags holds the value of the "tags" field.
	Tags []string `json:"tags,omitempty"`
	// Genders holds the value of the "genders" field.
	Genders []string `json:"genders,omitempty"`
	// Ethnicities holds the value of the "ethnicities" field.
	Ethnicities []string `json:"ethnicities,omitempty"`
	// Religions holds the value of the "religions" field.
	Religions []string `json:"religions,omitempty"`
	// DedicatedMajors holds the value of the "dedicated_majors" field.
	DedicatedMajors []string `json:"dedicated_majors,omitempty"`
	// Other holds the value of the "other" field.
	Other []string `json:"other,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the UserQuery when eager-loading is set.
	Edges        UserEdges `json:"edges"`
	selectValues sql.SelectValues
}

// UserEdges holds the relations/edges for other nodes in the graph.
type UserEdges struct {
	// LedClubs holds the value of the led_clubs edge.
	LedClubs []*Club `json:"led_clubs,omitempty"`
	// Answers holds the value of the answers edge.
	Answers []*Answer `json:"answers,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// LedClubsOrErr returns the LedClubs value or an error if the edge
// was not loaded in eager-loading.
func (e UserEdges) LedClubsOrErr() ([]*Club, error) {
	if e.loadedTypes[0] {
		return e.LedClubs, nil
	}
	return nil, &NotLoadedError{edge: "led_clubs"}
}

// AnswersOrErr returns the Answers value or an error if the edge
// was not loaded in eager-loading.
func (e UserEdges) AnswersOrErr() ([]*Answer, error) {
	if e.loadedTypes[1] {
		return e.Answers, nil
	}
	return nil, &NotLoadedError{edge: "answers"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*User) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case user.FieldTags, user.FieldGenders, user.FieldEthnicities, user.FieldReligions, user.FieldDedicatedMajors, user.FieldOther:
			values[i] = new([]byte)
		case user.FieldID:
			values[i] = new(sql.NullInt64)
		case user.FieldGoogleID, user.FieldEmail:
			values[i] = new(sql.NullString)
		case user.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the User fields.
func (_m *User) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case user.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case user.FieldGoogleID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field google_id", values[i])
			} else if value.Valid {
				_m.GoogleID = value.String
			}
		case user.FieldEmail:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field email", values[i])
			} else if value.Valid {
				_m.Email = value.String
			}
		case user.FieldTags:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field tags", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Tags); err != nil {
					return fmt.Errorf("unmarshal field tags: %w", err)
				}
			}
		case user.FieldGenders:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field genders", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Genders); err != nil {
					return fmt.Errorf("unmarshal field genders: %w", err)
				}
			}
		case user.FieldEthnicities:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field ethnicities", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Ethnicities); err != nil {
					return fmt.Errorf("unmarshal field ethnicities: %w", err)
				}
			}
		case user.FieldReligions:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field religions", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Religions); err != nil {
					return fmt.Errorf("unmarshal field religions: %w", err)
				}
			}
		case user.FieldDedicatedMajors:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field dedicated_majors", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.DedicatedMajors); err != nil {
					return fmt.Errorf("unmarshal field dedicated_majors: %w", err)
				}
			}
		case user.FieldOther:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field other", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Other); err != nil {
					return fmt.Errorf("unmarshal field other: %w", err)
				}
			}
		case user.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the User.
// This includes values selected through modifiers, order, etc.
func (_m *User) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryLedClubs queries the "led_clubs" edge of the User entity.
func (_m *User) QueryLedClubs() *ClubQuery {
	return NewUserClient(_m.config).QueryLedClubs(_m)
}

// QueryAnswers queries the "answers" edge of the User entity.
func (_m *User) QueryAnswers() *AnswerQuery {
	return NewUserClient(_m.config).QueryAnswers(_m)
}

// Update returns a builder for updating this User.
// Note that you need to call User.Unwrap() before calling this method if this User
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *User) Update() *UserUpdateOne {
	return NewUserClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the User entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *User) Unwrap() *User {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: User is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *User) String() string {
	var builder strings.Builder
	builder.WriteString("User(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("google_id=")
	builder.WriteString(_m.GoogleID)
	builder.WriteString(", ")
	builder.WriteString("email=")
	builder.WriteString(_m.Email)
	builder.WriteString(", ")
	builder.WriteString("tags=")
	builder.WriteString(fmt.Sprintf("%v", _m.Tags))
	builder.WriteString(", ")
	builder.WriteString("genders=")
	builder.WriteString(fmt.Sprintf("%v", _m.Genders))
	builder.WriteString(", ")
	builder.WriteString("ethnicities=")
	builder.WriteString(fmt.Sprintf("%v", _m.Ethnicities))
	builder.WriteString(", ")
	builder.WriteString("religions=")
	builder.WriteString(fmt.Sprintf("%v", _m.Religions))
	builder.WriteString(", ")
	builder.WriteString("dedicated_majors=")
	builder.WriteString(fmt.Sprintf("%v", _m.DedicatedMajors))
	builder.WriteString(", ")
	builder.WriteString("other=")
	builder.WriteString(fmt.Sprintf("%v", _m.Other))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Users is a parsable slice of User.
type Users []*User
