// Code generated by ent, DO NOT EDIT.

package club

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the club type in the database.
	Label = "club"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldClubName holds the string denoting the club_name field in the database.
	FieldClubName = "club_name"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldImagePath holds the string denoting the image_path field in the database.
	FieldImagePath = "image_path"
	// FieldExternalLink holds the string denoting the external_link field in the database.
	FieldExternalLink = "external_link"
	// FieldContactInfo holds the string denoting the contact_info field in the database.
	FieldContactInfo = "contact_info"
	// FieldIncludeOfficerEmails holds the string denoting the include_officer_emails field in the database.
	FieldIncludeOfficerEmails = "include_officer_emails"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeLeaders holds the string denoting the leaders edge name in mutations.
	EdgeLeaders = "leaders"
	// Table holds the table name of the club in the database.
	Table = "clubs"
	// LeadersTable is the table that holds the leaders relation/edge. The primary key declared below.
	LeadersTable = "club_leaders"
	// LeadersInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	LeadersInverseTable = "users"
)

// Columns holds all SQL columns for club fields.
var Columns = []string{
	FieldID,
	FieldClubName,
	FieldDescription,
	FieldImagePath,
	FieldExternalLink,
	FieldContactInfo,
	FieldIncludeOfficerEmails,
	FieldUpdatedAt,
}

var (
	// LeadersPrimaryKey and LeadersColumn2 are the table columns denoting the
	// primary key for the leaders relation (M2M).
	LeadersPrimaryKey = []string{"club_id", "user_id"}
)

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultIncludeOfficerEmails holds the default value on creation for the "include_officer_emails" field.
	DefaultIncludeOfficerEmails bool
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the Club queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByClubName orders the results by the club_name field.
func ByClubName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldClubName, opts...).ToFunc()
}

// ByDescription orders the results by the description field.
func ByDescription(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDescription, opts...).ToFunc()
}

// ByImagePath orders the results by the image_path field.
func ByImagePath(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldImagePath, opts...).ToFunc()
}

// ByExternalLink orders the results by the external_link field.
func ByExternalLink(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExternalLink, opts...).ToFunc()
}

// ByContactInfo orders the results by the contact_info field.
func ByContactInfo(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldContactInfo, opts...).ToFunc()
}

// ByIncludeOfficerEmails orders the results by the include_officer_emails field.
func ByIncludeOfficerEmails(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIncludeOfficerEmails, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByLeadersCount orders the results by leaders count.
func ByLeadersCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newLeadersStep(), opts...)
	}
}

// ByLeaders orders the results by leaders terms.
func ByLeaders(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newLeadersStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newLeadersStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(LeadersInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2M, false, LeadersTable, LeadersPrimaryKey...),
	)
}
