// Code generated by ent, DO NOT EDIT.

package answer

import (
	"su-organization-matching/server/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Answer {
	return predicate.Answer(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Answer {
	return predicate.Answer(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Answer {
	return predicate.Answer(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Answer {
	return predicate.Answer(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Answer {
	return predicate.Answer(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Answer {
	return predicate.Answer(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Answer {
	return predicate.Answer(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Answer {
	return predicate.Answer(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Answer {
	return predicate.Answer(sql.FieldLTE(FieldID, id))
}

// AnswerText applies equality check predicate on the "answer_text" field. It's identical to AnswerTextEQ.
func AnswerText(v string) predicate.Answer {
	return predicate.Answer(sql.FieldEQ(FieldAnswerText, v))
}

// SubmittedAt applies equality check predicate on the "submitted_at" field. It's identical to SubmittedAtEQ.
func SubmittedAt(v time.Time) predicate.Answer {
	return predicate.Answer(sql.FieldEQ(FieldSubmittedAt, v))
}

// AnswerTextEQ applies the EQ predicate on the "answer_text" field.
func AnswerTextEQ(v string) predicate.Answer {
	return predicate.Answer(sql.FieldEQ(FieldAnswerText, v))
}

// AnswerTextNEQ applies the NEQ predicate on the "answer_text" field.
func AnswerTextNEQ(v string) predicate.Answer {
	return predicate.Answer(sql.FieldNEQ(FieldAnswerText, v))
}

// AnswerTextIn applies the In predicate on the "answer_text" field.
func AnswerTextIn(vs ...string) predicate.Answer {
	return predicate.Answer(sql.FieldIn(FieldAnswerText, vs...))
}

// AnswerTextNotIn applies the NotIn predicate on the "answer_text" field.
func AnswerTextNotIn(vs ...string) predicate.Answer {
	return predicate.Answer(sql.FieldNotIn(FieldAnswerText, vs...))
}

// AnswerTextGT applies the GT predicate on the "answer_text" field.
func AnswerTextGT(v string) predicate.Answer {
	return predicate.Answer(sql.FieldGT(FieldAnswerText, v))
}

// AnswerTextGTE applies the GTE predicate on the "answer_text" field.
func AnswerTextGTE(v string) predicate.Answer {
	return predicate.Answer(sql.FieldGTE(FieldAnswerText, v))
}

// AnswerTextLT applies the LT predicate on the "answer_text" field.
func AnswerTextLT(v string) predicate.Answer {
	return predicate.Answer(sql.FieldLT(FieldAnswerText, v))
}

// AnswerTextLTE applies the LTE predicate on the "answer_text" field.
func AnswerTextLTE(v string) predicate.Answer {
	return predicate.Answer(sql.FieldLTE(FieldAnswerText, v))
}

// AnswerTextContains applies the Contains predicate on the "answer_text" field.
func AnswerTextContains(v string) predicate.Answer {
	return predicate.Answer(sql.FieldContains(FieldAnswerText, v))
}

// AnswerTextHasPrefix applies the HasPrefix predicate on the "answer_text" field.
func AnswerTextHasPrefix(v string) predicate.Answer {
	return predicate.Answer(sql.FieldHasPrefix(FieldAnswerText, v))
}

// AnswerTextHasSuffix applies the HasSuffix predicate on the "answer_text" field.
func AnswerTextHasSuffix(v string) predicate.Answer {
	return predicate.Answer(sql.FieldHasSuffix(FieldAnswerText, v))
}

// AnswerTextEqualFold applies the EqualFold predicate on the "answer_text" field.
func AnswerTextEqualFold(v string) predicate.Answer {
	return predicate.Answer(sql.FieldEqualFold(FieldAnswerText, v))
}

// AnswerTextContainsFold applies the ContainsFold predicate on the "answer_text" field.
func AnswerTextContainsFold(v string) predicate.Answer {
	return predicate.Answer(sql.FieldContainsFold(FieldAnswerText, v))
}

// SubmittedAtEQ applies the EQ predicate on the "submitted_at" field.
func SubmittedAtEQ(v time.Time) predicate.Answer {
	return predicate.Answer(sql.FieldEQ(FieldSubmittedAt, v))
}

// SubmittedAtNEQ applies the NEQ predicate on the "submitted_at" field.
func SubmittedAtNEQ(v time.Time) predicate.Answer {
	return predicate.Answer(sql.FieldNEQ(FieldSubmittedAt, v))
}

// SubmittedAtIn applies the In predicate on the "submitted_at" field.
func SubmittedAtIn(vs ...time.Time) predicate.Answer {
	return predicate.Answer(sql.FieldIn(FieldSubmittedAt, vs...))
}

// SubmittedAtNotIn applies the NotIn predicate on the "submitted_at" field.
func SubmittedAtNotIn(vs ...time.Time) predicate.Answer {
	return predicate.Answer(sql.FieldNotIn(FieldSubmittedAt, vs...))
}

// SubmittedAtGT applies the GT predicate on the "submitted_at" field.
func SubmittedAtGT(v time.Time) predicate.Answer {
	return predicate.Answer(sql.FieldGT(FieldSubmittedAt, v))
}

// SubmittedAtGTE applies the GTE predicate on the "submitted_at" field.
func SubmittedAtGTE(v time.Time) predicate.Answer {
	return predicate.Answer(sql.FieldGTE(FieldSubmittedAt, v))
}

// SubmittedAtLT applies the LT predicate on the "submitted_at" field.
func SubmittedAtLT(v time.Time) predicate.Answer {
	return predicate.Answer(sql.FieldLT(FieldSubmittedAt, v))
}

// SubmittedAtLTE applies the LTE predicate on the "submitted_at" field.
func SubmittedAtLTE(v time.Time) predicate.Answer {
	return predicate.Answer(sql.FieldLTE(FieldSubmittedAt, v))
}

// HasQuestion applies the HasEdge predicate on the "question" edge.
func HasQuestion() predicate.Answer {
	return predicate.Answer(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, QuestionTable, QuestionColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasQuestionWith applies the HasEdge predicate on the "question" edge with a given conditions (other predicates).
func HasQuestionWith(preds ...predicate.Question) predicate.Answer {
	return predicate.Answer(func(s *sql.Selector) {
		step := newQuestionStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.Answer {
	return predicate.Answer(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.Answer {
	return predicate.Answer(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Answer) predicate.Answer {
	return predicate.Answer(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Answer) predicate.Answer {
	return predicate.Answer(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Answer) predicate.Answer {
	return predicate.Answer(sql.NotPredicates(p))
}
