// Code generated by ent, DO NOT EDIT.

package ent

import (
	"server-example/ent/answer"
	"server-example/ent/club"
	"server-example/ent/question"
	"server-example/ent/schema"
	"server-example/ent/user"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	answerFields := schema.Answer{}.Fields()
	_ = answerFields
	// answerDescSubmittedAt is the schema descriptor for submitted_at field.
	answerDescSubmittedAt := answerFields[1].Descriptor()
	// answer.DefaultSubmittedAt holds the default value on creation for the submitted_at field.
	answer.DefaultSubmittedAt = answerDescSubmittedAt.Default.(func() time.Time)
	clubFields := schema.Club{}.Fields()
	_ = clubFields
	// clubDescIncludeOfficerEmails is the schema descriptor for include_officer_emails field.
	clubDescIncludeOfficerEmails := clubFields[5].Descriptor()
	// club.DefaultIncludeOfficerEmails holds the default value on creation for the include_officer_emails field.
	club.DefaultIncludeOfficerEmails = clubDescIncludeOfficerEmails.Default.(bool)
	// clubDescUpdatedAt is the schema descriptor for updated_at field.
	clubDescUpdatedAt := clubFields[6].Descriptor()
	// club.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	club.DefaultUpdatedAt = clubDescUpdatedAt.Default.(func() time.Time)
	// club.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	club.UpdateDefaultUpdatedAt = clubDescUpdatedAt.UpdateDefault.(func() time.Time)
	questionFields := schema.Question{}.Fields()
	_ = questionFields
	// questionDescIsActive is the schema descriptor for is_active field.
	questionDescIsActive := questionFields[2].Descriptor()
	// question.DefaultIsActive holds the default value on creation for the is_active field.
	question.DefaultIsActive = questionDescIsActive.Default.(bool)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescTags is the schema descriptor for tags field.
	userDescTags := userFields[2].Descriptor()
	// user.DefaultTags holds the default value on creation for the tags field.
	user.DefaultTags = userDescTags.Default.([]string)
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userFields[3].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
}
