// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// AnswersColumns holds the columns for the "answers" table.
	AnswersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "answer_text", Type: field.TypeString, Size: 2147483647},
		{Name: "submitted_at", Type: field.TypeTime},
		{Name: "question_answers", Type: field.TypeInt},
		{Name: "user_answers", Type: field.TypeInt},
	}
	// AnswersTable holds the schema information for the "answers" table.
	AnswersTable = &schema.Table{
		Name:       "answers",
		Columns:    AnswersColumns,
		PrimaryKey: []*schema.Column{AnswersColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "answers_questions_answers",
				Columns:    []*schema.Column{AnswersColumns[3]},
				RefColumns: []*schema.Column{QuestionsColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "answers_users_answers",
				Columns:    []*schema.Column{AnswersColumns[4]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// ClubsColumns holds the columns for the "clubs" table.
	ClubsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "club_name", Type: field.TypeString},
		{Name: "description", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "meeting_time", Type: field.TypeString, Nullable: true},
		{Name: "image_path", Type: field.TypeString, Nullable: true},
		{Name: "external_link", Type: field.TypeString, Nullable: true},
		{Name: "contact_info", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "include_officer_emails", Type: field.TypeBool, Default: false},
		{Name: "personality", Type: field.TypeJSON},
		{Name: "activities", Type: field.TypeJSON},
		{Name: "genders", Type: field.TypeJSON},
		{Name: "ethnicities", Type: field.TypeJSON},
		{Name: "religions", Type: field.TypeJSON},
		{Name: "strict_genders", Type: field.TypeBool, Default: false},
		{Name: "dedicated_majors", Type: field.TypeJSON},
		{Name: "associated_majors", Type: field.TypeJSON},
		{Name: "other", Type: field.TypeJSON},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// ClubsTable holds the schema information for the "clubs" table.
	ClubsTable = &schema.Table{
		Name:       "clubs",
		Columns:    ClubsColumns,
		PrimaryKey: []*schema.Column{ClubsColumns[0]},
	}
	// QuestionsColumns holds the columns for the "questions" table.
	QuestionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "question_type", Type: field.TypeString},
		{Name: "translations", Type: field.TypeJSON},
		{Name: "is_active", Type: field.TypeBool, Default: true},
	}
	// QuestionsTable holds the schema information for the "questions" table.
	QuestionsTable = &schema.Table{
		Name:       "questions",
		Columns:    QuestionsColumns,
		PrimaryKey: []*schema.Column{QuestionsColumns[0]},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "google_id", Type: field.TypeString, Unique: true},
		{Name: "email", Type: field.TypeString, Unique: true},
		{Name: "tags", Type: field.TypeJSON},
		{Name: "genders", Type: field.TypeJSON},
		{Name: "ethnicities", Type: field.TypeJSON},
		{Name: "religions", Type: field.TypeJSON},
		{Name: "dedicated_majors", Type: field.TypeJSON},
		{Name: "other", Type: field.TypeJSON},
		{Name: "created_at", Type: field.TypeTime},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	// ClubLeadersColumns holds the columns for the "club_leaders" table.
	ClubLeadersColumns = []*schema.Column{
		{Name: "club_id", Type: field.TypeInt},
		{Name: "user_id", Type: field.TypeInt},
	}
	// ClubLeadersTable holds the schema information for the "club_leaders" table.
	ClubLeadersTable = &schema.Table{
		Name:       "club_leaders",
		Columns:    ClubLeadersColumns,
		PrimaryKey: []*schema.Column{ClubLeadersColumns[0], ClubLeadersColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "club_leaders_club_id",
				Columns:    []*schema.Column{ClubLeadersColumns[0]},
				RefColumns: []*schema.Column{ClubsColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "club_leaders_user_id",
				Columns:    []*schema.Column{ClubLeadersColumns[1]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		AnswersTable,
		ClubsTable,
		QuestionsTable,
		UsersTable,
		ClubLeadersTable,
	}
)

func init() {
	AnswersTable.ForeignKeys[0].RefTable = QuestionsTable
	AnswersTable.ForeignKeys[1].RefTable = UsersTable
	ClubLeadersTable.ForeignKeys[0].RefTable = ClubsTable
	ClubLeadersTable.ForeignKeys[1].RefTable = UsersTable
}
