// Code generated by ent, DO NOT EDIT.

package question

import (
	"server-example/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Question {
	return predicate.Question(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Question {
	return predicate.Question(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Question {
	return predicate.Question(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Question {
	return predicate.Question(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Question {
	return predicate.Question(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Question {
	return predicate.Question(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Question {
	return predicate.Question(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Question {
	return predicate.Question(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Question {
	return predicate.Question(sql.FieldLTE(FieldID, id))
}

// QuestionType applies equality check predicate on the "question_type" field. It's identical to QuestionTypeEQ.
func QuestionType(v string) predicate.Question {
	return predicate.Question(sql.FieldEQ(FieldQuestionType, v))
}

// IsActive applies equality check predicate on the "is_active" field. It's identical to IsActiveEQ.
func IsActive(v bool) predicate.Question {
	return predicate.Question(sql.FieldEQ(FieldIsActive, v))
}

// QuestionTypeEQ applies the EQ predicate on the "question_type" field.
func QuestionTypeEQ(v string) predicate.Question {
	return predicate.Question(sql.FieldEQ(FieldQuestionType, v))
}

// QuestionTypeNEQ applies the NEQ predicate on the "question_type" field.
func QuestionTypeNEQ(v string) predicate.Question {
	return predicate.Question(sql.FieldNEQ(FieldQuestionType, v))
}

// QuestionTypeIn applies the In predicate on the "question_type" field.
func QuestionTypeIn(vs ...string) predicate.Question {
	return predicate.Question(sql.FieldIn(FieldQuestionType, vs...))
}

// QuestionTypeNotIn applies the NotIn predicate on the "question_type" field.
func QuestionTypeNotIn(vs ...string) predicate.Question {
	return predicate.Question(sql.FieldNotIn(FieldQuestionType, vs...))
}

// QuestionTypeGT applies the GT predicate on the "question_type" field.
func QuestionTypeGT(v string) predicate.Question {
	return predicate.Question(sql.FieldGT(FieldQuestionType, v))
}

// QuestionTypeGTE applies the GTE predicate on the "question_type" field.
func QuestionTypeGTE(v string) predicate.Question {
	return predicate.Question(sql.FieldGTE(FieldQuestionType, v))
}

// QuestionTypeLT applies the LT predicate on the "question_type" field.
func QuestionTypeLT(v string) predicate.Question {
	return predicate.Question(sql.FieldLT(FieldQuestionType, v))
}

// QuestionTypeLTE applies the LTE predicate on the "question_type" field.
func QuestionTypeLTE(v string) predicate.Question {
	return predicate.Question(sql.FieldLTE(FieldQuestionType, v))
}

// QuestionTypeContains applies the Contains predicate on the "question_type" field.
func QuestionTypeContains(v string) predicate.Question {
	return predicate.Question(sql.FieldContains(FieldQuestionType, v))
}

// QuestionTypeHasPrefix applies the HasPrefix predicate on the "question_type" field.
func QuestionTypeHasPrefix(v string) predicate.Question {
	return predicate.Question(sql.FieldHasPrefix(FieldQuestionType, v))
}

// QuestionTypeHasSuffix applies the HasSuffix predicate on the "question_type" field.
func QuestionTypeHasSuffix(v string) predicate.Question {
	return predicate.Question(sql.FieldHasSuffix(FieldQuestionType, v))
}

// QuestionTypeEqualFold applies the EqualFold predicate on the "question_type" field.
func QuestionTypeEqualFold(v string) predicate.Question {
	return predicate.Question(sql.FieldEqualFold(FieldQuestionType, v))
}

// QuestionTypeContainsFold applies the ContainsFold predicate on the "question_type" field.
func QuestionTypeContainsFold(v string) predicate.Question {
	return predicate.Question(sql.FieldContainsFold(FieldQuestionType, v))
}

// IsActiveEQ applies the EQ predicate on the "is_active" field.
func IsActiveEQ(v bool) predicate.Question {
	return predicate.Question(sql.FieldEQ(FieldIsActive, v))
}

// IsActiveNEQ applies the NEQ predicate on the "is_active" field.
func IsActiveNEQ(v bool) predicate.Question {
	return predicate.Question(sql.FieldNEQ(FieldIsActive, v))
}

// HasAnswers applies the HasEdge predicate on the "answers" edge.
func HasAnswers() predicate.Question {
	return predicate.Question(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, AnswersTable, AnswersColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAnswersWith applies the HasEdge predicate on the "answers" edge with a given conditions (other predicates).
func HasAnswersWith(preds ...predicate.Answer) predicate.Question {
	return predicate.Question(func(s *sql.Selector) {
		step := newAnswersStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Question) predicate.Question {
	return predicate.Question(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Question) predicate.Question {
	return predicate.Question(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Question) predicate.Question {
	return predicate.Question(sql.NotPredicates(p))
}
