// Code generated by ent, DO NOT EDIT.

package club

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the club type in the database.
	Label = "club"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldClubName holds the string denoting the club_name field in the database.
	FieldClubName = "club_name"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldMeetingTime holds the string denoting the meeting_time field in the database.
	FieldMeetingTime = "meeting_time"
	// FieldImagePath holds the string denoting the image_path field in the database.
	FieldImagePath = "image_path"
	// FieldExternalLink holds the string denoting the external_link field in the database.
	FieldExternalLink = "external_link"
	// FieldContactInfo holds the string denoting the contact_info field in the database.
	FieldContactInfo = "contact_info"
	// FieldIncludeOfficerEmails holds the string denoting the include_officer_emails field in the database.
	FieldIncludeOfficerEmails = "include_officer_emails"
	// FieldPersonality holds the string denoting the personality field in the database.
	FieldPersonality = "personality"
	// FieldActivities holds the string denoting the activities field in the database.
	FieldActivities = "activities"
	// FieldActivitiesDescription holds the string denoting the activities_description field in the database.
	FieldActivitiesDescription = "activities_description"
	// FieldGenders holds the string denoting the genders field in the database.
	FieldGenders = "genders"
	// FieldEthnicities holds the string denoting the ethnicities field in the database.
	FieldEthnicities = "ethnicities"
	// FieldReligions holds the string denoting the religions field in the database.
	FieldReligions = "religions"
	// FieldStrictGenders holds the string denoting the strict_genders field in the database.
	FieldStrictGenders = "strict_genders"
	// FieldDedicatedMajors holds the string denoting the dedicated_majors field in the database.
	FieldDedicatedMajors = "dedicated_majors"
	// FieldAssociatedMajors holds the string denoting the associated_majors field in the database.
	FieldAssociatedMajors = "associated_majors"
	// FieldOther holds the string denoting the other field in the database.
	FieldOther = "other"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeLeaders holds the string denoting the leaders edge name in mutations.
	EdgeLeaders = "leaders"
	// Table holds the table name of the club in the database.
	Table = "clubs"
	// LeadersTable is the table that holds the leaders relation/edge. The primary key declared below.
	LeadersTable = "club_leaders"
	// LeadersInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	LeadersInverseTable = "users"
)

// Columns holds all SQL columns for club fields.
var Columns = []string{
	FieldID,
	FieldClubName,
	FieldDescription,
	FieldMeetingTime,
	FieldImagePath,
	FieldExternalLink,
	FieldContactInfo,
	FieldIncludeOfficerEmails,
	FieldPersonality,
	FieldActivities,
	FieldActivitiesDescription,
	FieldGenders,
	FieldEthnicities,
	FieldReligions,
	FieldStrictGenders,
	FieldDedicatedMajors,
	FieldAssociatedMajors,
	FieldOther,
	FieldUpdatedAt,
}

var (
	// LeadersPrimaryKey and LeadersColumn2 are the table columns denoting the
	// primary key for the leaders relation (M2M).
	LeadersPrimaryKey = []string{"club_id", "user_id"}
)

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultIncludeOfficerEmails holds the default value on creation for the "include_officer_emails" field.
	DefaultIncludeOfficerEmails bool
	// DefaultPersonality holds the default value on creation for the "personality" field.
	DefaultPersonality []string
	// DefaultActivities holds the default value on creation for the "activities" field.
	DefaultActivities []string
	// DefaultActivitiesDescription holds the default value on creation for the "activities_description" field.
	DefaultActivitiesDescription string
	// DefaultGenders holds the default value on creation for the "genders" field.
	DefaultGenders []string
	// DefaultEthnicities holds the default value on creation for the "ethnicities" field.
	DefaultEthnicities []string
	// DefaultReligions holds the default value on creation for the "religions" field.
	DefaultReligions []string
	// DefaultStrictGenders holds the default value on creation for the "strict_genders" field.
	DefaultStrictGenders bool
	// DefaultDedicatedMajors holds the default value on creation for the "dedicated_majors" field.
	DefaultDedicatedMajors []string
	// DefaultAssociatedMajors holds the default value on creation for the "associated_majors" field.
	DefaultAssociatedMajors []string
	// DefaultOther holds the default value on creation for the "other" field.
	DefaultOther []string
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the Club queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByClubName orders the results by the club_name field.
func ByClubName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldClubName, opts...).ToFunc()
}

// ByDescription orders the results by the description field.
func ByDescription(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDescription, opts...).ToFunc()
}

// ByMeetingTime orders the results by the meeting_time field.
func ByMeetingTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMeetingTime, opts...).ToFunc()
}

// ByImagePath orders the results by the image_path field.
func ByImagePath(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldImagePath, opts...).ToFunc()
}

// ByExternalLink orders the results by the external_link field.
func ByExternalLink(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExternalLink, opts...).ToFunc()
}

// ByContactInfo orders the results by the contact_info field.
func ByContactInfo(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldContactInfo, opts...).ToFunc()
}

// ByIncludeOfficerEmails orders the results by the include_officer_emails field.
func ByIncludeOfficerEmails(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIncludeOfficerEmails, opts...).ToFunc()
}

// ByActivitiesDescription orders the results by the activities_description field.
func ByActivitiesDescription(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldActivitiesDescription, opts...).ToFunc()
}

// ByStrictGenders orders the results by the strict_genders field.
func ByStrictGenders(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStrictGenders, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByLeadersCount orders the results by leaders count.
func ByLeadersCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newLeadersStep(), opts...)
	}
}

// ByLeaders orders the results by leaders terms.
func ByLeaders(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newLeadersStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newLeadersStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(LeadersInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2M, false, LeadersTable, LeadersPrimaryKey...),
	)
}
