// Code generated by ent, DO NOT EDIT.

package club

import (
	"server-example/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Club {
	return predicate.Club(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Club {
	return predicate.Club(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Club {
	return predicate.Club(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Club {
	return predicate.Club(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Club {
	return predicate.Club(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Club {
	return predicate.Club(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Club {
	return predicate.Club(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Club {
	return predicate.Club(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Club {
	return predicate.Club(sql.FieldLTE(FieldID, id))
}

// ClubName applies equality check predicate on the "club_name" field. It's identical to ClubNameEQ.
func ClubName(v string) predicate.Club {
	return predicate.Club(sql.FieldEQ(FieldClubName, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.Club {
	return predicate.Club(sql.FieldEQ(FieldDescription, v))
}

// MeetingTime applies equality check predicate on the "meeting_time" field. It's identical to MeetingTimeEQ.
func MeetingTime(v string) predicate.Club {
	return predicate.Club(sql.FieldEQ(FieldMeetingTime, v))
}

// ImagePath applies equality check predicate on the "image_path" field. It's identical to ImagePathEQ.
func ImagePath(v string) predicate.Club {
	return predicate.Club(sql.FieldEQ(FieldImagePath, v))
}

// ExternalLink applies equality check predicate on the "external_link" field. It's identical to ExternalLinkEQ.
func ExternalLink(v string) predicate.Club {
	return predicate.Club(sql.FieldEQ(FieldExternalLink, v))
}

// ContactInfo applies equality check predicate on the "contact_info" field. It's identical to ContactInfoEQ.
func ContactInfo(v string) predicate.Club {
	return predicate.Club(sql.FieldEQ(FieldContactInfo, v))
}

// IncludeOfficerEmails applies equality check predicate on the "include_officer_emails" field. It's identical to IncludeOfficerEmailsEQ.
func IncludeOfficerEmails(v bool) predicate.Club {
	return predicate.Club(sql.FieldEQ(FieldIncludeOfficerEmails, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Club {
	return predicate.Club(sql.FieldEQ(FieldUpdatedAt, v))
}

// ClubNameEQ applies the EQ predicate on the "club_name" field.
func ClubNameEQ(v string) predicate.Club {
	return predicate.Club(sql.FieldEQ(FieldClubName, v))
}

// ClubNameNEQ applies the NEQ predicate on the "club_name" field.
func ClubNameNEQ(v string) predicate.Club {
	return predicate.Club(sql.FieldNEQ(FieldClubName, v))
}

// ClubNameIn applies the In predicate on the "club_name" field.
func ClubNameIn(vs ...string) predicate.Club {
	return predicate.Club(sql.FieldIn(FieldClubName, vs...))
}

// ClubNameNotIn applies the NotIn predicate on the "club_name" field.
func ClubNameNotIn(vs ...string) predicate.Club {
	return predicate.Club(sql.FieldNotIn(FieldClubName, vs...))
}

// ClubNameGT applies the GT predicate on the "club_name" field.
func ClubNameGT(v string) predicate.Club {
	return predicate.Club(sql.FieldGT(FieldClubName, v))
}

// ClubNameGTE applies the GTE predicate on the "club_name" field.
func ClubNameGTE(v string) predicate.Club {
	return predicate.Club(sql.FieldGTE(FieldClubName, v))
}

// ClubNameLT applies the LT predicate on the "club_name" field.
func ClubNameLT(v string) predicate.Club {
	return predicate.Club(sql.FieldLT(FieldClubName, v))
}

// ClubNameLTE applies the LTE predicate on the "club_name" field.
func ClubNameLTE(v string) predicate.Club {
	return predicate.Club(sql.FieldLTE(FieldClubName, v))
}

// ClubNameContains applies the Contains predicate on the "club_name" field.
func ClubNameContains(v string) predicate.Club {
	return predicate.Club(sql.FieldContains(FieldClubName, v))
}

// ClubNameHasPrefix applies the HasPrefix predicate on the "club_name" field.
func ClubNameHasPrefix(v string) predicate.Club {
	return predicate.Club(sql.FieldHasPrefix(FieldClubName, v))
}

// ClubNameHasSuffix applies the HasSuffix predicate on the "club_name" field.
func ClubNameHasSuffix(v string) predicate.Club {
	return predicate.Club(sql.FieldHasSuffix(FieldClubName, v))
}

// ClubNameEqualFold applies the EqualFold predicate on the "club_name" field.
func ClubNameEqualFold(v string) predicate.Club {
	return predicate.Club(sql.FieldEqualFold(FieldClubName, v))
}

// ClubNameContainsFold applies the ContainsFold predicate on the "club_name" field.
func ClubNameContainsFold(v string) predicate.Club {
	return predicate.Club(sql.FieldContainsFold(FieldClubName, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.Club {
	return predicate.Club(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.Club {
	return predicate.Club(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.Club {
	return predicate.Club(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.Club {
	return predicate.Club(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.Club {
	return predicate.Club(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.Club {
	return predicate.Club(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.Club {
	return predicate.Club(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.Club {
	return predicate.Club(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.Club {
	return predicate.Club(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.Club {
	return predicate.Club(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.Club {
	return predicate.Club(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionIsNil applies the IsNil predicate on the "description" field.
func DescriptionIsNil() predicate.Club {
	return predicate.Club(sql.FieldIsNull(FieldDescription))
}

// DescriptionNotNil applies the NotNil predicate on the "description" field.
func DescriptionNotNil() predicate.Club {
	return predicate.Club(sql.FieldNotNull(FieldDescription))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.Club {
	return predicate.Club(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.Club {
	return predicate.Club(sql.FieldContainsFold(FieldDescription, v))
}

// MeetingTimeEQ applies the EQ predicate on the "meeting_time" field.
func MeetingTimeEQ(v string) predicate.Club {
	return predicate.Club(sql.FieldEQ(FieldMeetingTime, v))
}

// MeetingTimeNEQ applies the NEQ predicate on the "meeting_time" field.
func MeetingTimeNEQ(v string) predicate.Club {
	return predicate.Club(sql.FieldNEQ(FieldMeetingTime, v))
}

// MeetingTimeIn applies the In predicate on the "meeting_time" field.
func MeetingTimeIn(vs ...string) predicate.Club {
	return predicate.Club(sql.FieldIn(FieldMeetingTime, vs...))
}

// MeetingTimeNotIn applies the NotIn predicate on the "meeting_time" field.
func MeetingTimeNotIn(vs ...string) predicate.Club {
	return predicate.Club(sql.FieldNotIn(FieldMeetingTime, vs...))
}

// MeetingTimeGT applies the GT predicate on the "meeting_time" field.
func MeetingTimeGT(v string) predicate.Club {
	return predicate.Club(sql.FieldGT(FieldMeetingTime, v))
}

// MeetingTimeGTE applies the GTE predicate on the "meeting_time" field.
func MeetingTimeGTE(v string) predicate.Club {
	return predicate.Club(sql.FieldGTE(FieldMeetingTime, v))
}

// MeetingTimeLT applies the LT predicate on the "meeting_time" field.
func MeetingTimeLT(v string) predicate.Club {
	return predicate.Club(sql.FieldLT(FieldMeetingTime, v))
}

// MeetingTimeLTE applies the LTE predicate on the "meeting_time" field.
func MeetingTimeLTE(v string) predicate.Club {
	return predicate.Club(sql.FieldLTE(FieldMeetingTime, v))
}

// MeetingTimeContains applies the Contains predicate on the "meeting_time" field.
func MeetingTimeContains(v string) predicate.Club {
	return predicate.Club(sql.FieldContains(FieldMeetingTime, v))
}

// MeetingTimeHasPrefix applies the HasPrefix predicate on the "meeting_time" field.
func MeetingTimeHasPrefix(v string) predicate.Club {
	return predicate.Club(sql.FieldHasPrefix(FieldMeetingTime, v))
}

// MeetingTimeHasSuffix applies the HasSuffix predicate on the "meeting_time" field.
func MeetingTimeHasSuffix(v string) predicate.Club {
	return predicate.Club(sql.FieldHasSuffix(FieldMeetingTime, v))
}

// MeetingTimeIsNil applies the IsNil predicate on the "meeting_time" field.
func MeetingTimeIsNil() predicate.Club {
	return predicate.Club(sql.FieldIsNull(FieldMeetingTime))
}

// MeetingTimeNotNil applies the NotNil predicate on the "meeting_time" field.
func MeetingTimeNotNil() predicate.Club {
	return predicate.Club(sql.FieldNotNull(FieldMeetingTime))
}

// MeetingTimeEqualFold applies the EqualFold predicate on the "meeting_time" field.
func MeetingTimeEqualFold(v string) predicate.Club {
	return predicate.Club(sql.FieldEqualFold(FieldMeetingTime, v))
}

// MeetingTimeContainsFold applies the ContainsFold predicate on the "meeting_time" field.
func MeetingTimeContainsFold(v string) predicate.Club {
	return predicate.Club(sql.FieldContainsFold(FieldMeetingTime, v))
}

// ImagePathEQ applies the EQ predicate on the "image_path" field.
func ImagePathEQ(v string) predicate.Club {
	return predicate.Club(sql.FieldEQ(FieldImagePath, v))
}

// ImagePathNEQ applies the NEQ predicate on the "image_path" field.
func ImagePathNEQ(v string) predicate.Club {
	return predicate.Club(sql.FieldNEQ(FieldImagePath, v))
}

// ImagePathIn applies the In predicate on the "image_path" field.
func ImagePathIn(vs ...string) predicate.Club {
	return predicate.Club(sql.FieldIn(FieldImagePath, vs...))
}

// ImagePathNotIn applies the NotIn predicate on the "image_path" field.
func ImagePathNotIn(vs ...string) predicate.Club {
	return predicate.Club(sql.FieldNotIn(FieldImagePath, vs...))
}

// ImagePathGT applies the GT predicate on the "image_path" field.
func ImagePathGT(v string) predicate.Club {
	return predicate.Club(sql.FieldGT(FieldImagePath, v))
}

// ImagePathGTE applies the GTE predicate on the "image_path" field.
func ImagePathGTE(v string) predicate.Club {
	return predicate.Club(sql.FieldGTE(FieldImagePath, v))
}

// ImagePathLT applies the LT predicate on the "image_path" field.
func ImagePathLT(v string) predicate.Club {
	return predicate.Club(sql.FieldLT(FieldImagePath, v))
}

// ImagePathLTE applies the LTE predicate on the "image_path" field.
func ImagePathLTE(v string) predicate.Club {
	return predicate.Club(sql.FieldLTE(FieldImagePath, v))
}

// ImagePathContains applies the Contains predicate on the "image_path" field.
func ImagePathContains(v string) predicate.Club {
	return predicate.Club(sql.FieldContains(FieldImagePath, v))
}

// ImagePathHasPrefix applies the HasPrefix predicate on the "image_path" field.
func ImagePathHasPrefix(v string) predicate.Club {
	return predicate.Club(sql.FieldHasPrefix(FieldImagePath, v))
}

// ImagePathHasSuffix applies the HasSuffix predicate on the "image_path" field.
func ImagePathHasSuffix(v string) predicate.Club {
	return predicate.Club(sql.FieldHasSuffix(FieldImagePath, v))
}

// ImagePathIsNil applies the IsNil predicate on the "image_path" field.
func ImagePathIsNil() predicate.Club {
	return predicate.Club(sql.FieldIsNull(FieldImagePath))
}

// ImagePathNotNil applies the NotNil predicate on the "image_path" field.
func ImagePathNotNil() predicate.Club {
	return predicate.Club(sql.FieldNotNull(FieldImagePath))
}

// ImagePathEqualFold applies the EqualFold predicate on the "image_path" field.
func ImagePathEqualFold(v string) predicate.Club {
	return predicate.Club(sql.FieldEqualFold(FieldImagePath, v))
}

// ImagePathContainsFold applies the ContainsFold predicate on the "image_path" field.
func ImagePathContainsFold(v string) predicate.Club {
	return predicate.Club(sql.FieldContainsFold(FieldImagePath, v))
}

// ExternalLinkEQ applies the EQ predicate on the "external_link" field.
func ExternalLinkEQ(v string) predicate.Club {
	return predicate.Club(sql.FieldEQ(FieldExternalLink, v))
}

// ExternalLinkNEQ applies the NEQ predicate on the "external_link" field.
func ExternalLinkNEQ(v string) predicate.Club {
	return predicate.Club(sql.FieldNEQ(FieldExternalLink, v))
}

// ExternalLinkIn applies the In predicate on the "external_link" field.
func ExternalLinkIn(vs ...string) predicate.Club {
	return predicate.Club(sql.FieldIn(FieldExternalLink, vs...))
}

// ExternalLinkNotIn applies the NotIn predicate on the "external_link" field.
func ExternalLinkNotIn(vs ...string) predicate.Club {
	return predicate.Club(sql.FieldNotIn(FieldExternalLink, vs...))
}

// ExternalLinkGT applies the GT predicate on the "external_link" field.
func ExternalLinkGT(v string) predicate.Club {
	return predicate.Club(sql.FieldGT(FieldExternalLink, v))
}

// ExternalLinkGTE applies the GTE predicate on the "external_link" field.
func ExternalLinkGTE(v string) predicate.Club {
	return predicate.Club(sql.FieldGTE(FieldExternalLink, v))
}

// ExternalLinkLT applies the LT predicate on the "external_link" field.
func ExternalLinkLT(v string) predicate.Club {
	return predicate.Club(sql.FieldLT(FieldExternalLink, v))
}

// ExternalLinkLTE applies the LTE predicate on the "external_link" field.
func ExternalLinkLTE(v string) predicate.Club {
	return predicate.Club(sql.FieldLTE(FieldExternalLink, v))
}

// ExternalLinkContains applies the Contains predicate on the "external_link" field.
func ExternalLinkContains(v string) predicate.Club {
	return predicate.Club(sql.FieldContains(FieldExternalLink, v))
}

// ExternalLinkHasPrefix applies the HasPrefix predicate on the "external_link" field.
func ExternalLinkHasPrefix(v string) predicate.Club {
	return predicate.Club(sql.FieldHasPrefix(FieldExternalLink, v))
}

// ExternalLinkHasSuffix applies the HasSuffix predicate on the "external_link" field.
func ExternalLinkHasSuffix(v string) predicate.Club {
	return predicate.Club(sql.FieldHasSuffix(FieldExternalLink, v))
}

// ExternalLinkIsNil applies the IsNil predicate on the "external_link" field.
func ExternalLinkIsNil() predicate.Club {
	return predicate.Club(sql.FieldIsNull(FieldExternalLink))
}

// ExternalLinkNotNil applies the NotNil predicate on the "external_link" field.
func ExternalLinkNotNil() predicate.Club {
	return predicate.Club(sql.FieldNotNull(FieldExternalLink))
}

// ExternalLinkEqualFold applies the EqualFold predicate on the "external_link" field.
func ExternalLinkEqualFold(v string) predicate.Club {
	return predicate.Club(sql.FieldEqualFold(FieldExternalLink, v))
}

// ExternalLinkContainsFold applies the ContainsFold predicate on the "external_link" field.
func ExternalLinkContainsFold(v string) predicate.Club {
	return predicate.Club(sql.FieldContainsFold(FieldExternalLink, v))
}

// ContactInfoEQ applies the EQ predicate on the "contact_info" field.
func ContactInfoEQ(v string) predicate.Club {
	return predicate.Club(sql.FieldEQ(FieldContactInfo, v))
}

// ContactInfoNEQ applies the NEQ predicate on the "contact_info" field.
func ContactInfoNEQ(v string) predicate.Club {
	return predicate.Club(sql.FieldNEQ(FieldContactInfo, v))
}

// ContactInfoIn applies the In predicate on the "contact_info" field.
func ContactInfoIn(vs ...string) predicate.Club {
	return predicate.Club(sql.FieldIn(FieldContactInfo, vs...))
}

// ContactInfoNotIn applies the NotIn predicate on the "contact_info" field.
func ContactInfoNotIn(vs ...string) predicate.Club {
	return predicate.Club(sql.FieldNotIn(FieldContactInfo, vs...))
}

// ContactInfoGT applies the GT predicate on the "contact_info" field.
func ContactInfoGT(v string) predicate.Club {
	return predicate.Club(sql.FieldGT(FieldContactInfo, v))
}

// ContactInfoGTE applies the GTE predicate on the "contact_info" field.
func ContactInfoGTE(v string) predicate.Club {
	return predicate.Club(sql.FieldGTE(FieldContactInfo, v))
}

// ContactInfoLT applies the LT predicate on the "contact_info" field.
func ContactInfoLT(v string) predicate.Club {
	return predicate.Club(sql.FieldLT(FieldContactInfo, v))
}

// ContactInfoLTE applies the LTE predicate on the "contact_info" field.
func ContactInfoLTE(v string) predicate.Club {
	return predicate.Club(sql.FieldLTE(FieldContactInfo, v))
}

// ContactInfoContains applies the Contains predicate on the "contact_info" field.
func ContactInfoContains(v string) predicate.Club {
	return predicate.Club(sql.FieldContains(FieldContactInfo, v))
}

// ContactInfoHasPrefix applies the HasPrefix predicate on the "contact_info" field.
func ContactInfoHasPrefix(v string) predicate.Club {
	return predicate.Club(sql.FieldHasPrefix(FieldContactInfo, v))
}

// ContactInfoHasSuffix applies the HasSuffix predicate on the "contact_info" field.
func ContactInfoHasSuffix(v string) predicate.Club {
	return predicate.Club(sql.FieldHasSuffix(FieldContactInfo, v))
}

// ContactInfoIsNil applies the IsNil predicate on the "contact_info" field.
func ContactInfoIsNil() predicate.Club {
	return predicate.Club(sql.FieldIsNull(FieldContactInfo))
}

// ContactInfoNotNil applies the NotNil predicate on the "contact_info" field.
func ContactInfoNotNil() predicate.Club {
	return predicate.Club(sql.FieldNotNull(FieldContactInfo))
}

// ContactInfoEqualFold applies the EqualFold predicate on the "contact_info" field.
func ContactInfoEqualFold(v string) predicate.Club {
	return predicate.Club(sql.FieldEqualFold(FieldContactInfo, v))
}

// ContactInfoContainsFold applies the ContainsFold predicate on the "contact_info" field.
func ContactInfoContainsFold(v string) predicate.Club {
	return predicate.Club(sql.FieldContainsFold(FieldContactInfo, v))
}

// IncludeOfficerEmailsEQ applies the EQ predicate on the "include_officer_emails" field.
func IncludeOfficerEmailsEQ(v bool) predicate.Club {
	return predicate.Club(sql.FieldEQ(FieldIncludeOfficerEmails, v))
}

// IncludeOfficerEmailsNEQ applies the NEQ predicate on the "include_officer_emails" field.
func IncludeOfficerEmailsNEQ(v bool) predicate.Club {
	return predicate.Club(sql.FieldNEQ(FieldIncludeOfficerEmails, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Club {
	return predicate.Club(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Club {
	return predicate.Club(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Club {
	return predicate.Club(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Club {
	return predicate.Club(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Club {
	return predicate.Club(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Club {
	return predicate.Club(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Club {
	return predicate.Club(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Club {
	return predicate.Club(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasLeaders applies the HasEdge predicate on the "leaders" edge.
func HasLeaders() predicate.Club {
	return predicate.Club(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2M, false, LeadersTable, LeadersPrimaryKey...),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasLeadersWith applies the HasEdge predicate on the "leaders" edge with a given conditions (other predicates).
func HasLeadersWith(preds ...predicate.User) predicate.Club {
	return predicate.Club(func(s *sql.Selector) {
		step := newLeadersStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Club) predicate.Club {
	return predicate.Club(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Club) predicate.Club {
	return predicate.Club(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Club) predicate.Club {
	return predicate.Club(sql.NotPredicates(p))
}
